import { createNewGame } from '../systems/CharacterSystem';
import { ageUp } from '../systems/AgingSystem';
import { processDelayedEvents, resolvePendingEvent } from '../systems/EventSystem';
import { processAnnualFinance } from '../systems/FinanceSystem';
import { migrateSave } from '../services/SaveSystem';

export function runHouseholdFinanceRegression(){let checks=0;const verify=(condition:unknown,message:string)=>{checks++;if(!condition)throw new Error(`Household finance regression failed: ${message}`);};
  const newborn=createNewGame({seed:'household-newborn'});verify(newborn.finances.cash===0,'newborn starts with zero personal cash');verify(newborn.flags.financiallyIndependent===false,'newborn starts household-supported');verify(newborn.relationships.filter(r=>r.type==='parent'&&newborn.npcs[r.npcId]?.alive).length===2,'ordinary generated life starts with two living parent NPCs');
  for(let age=1;age<=17;age++){newborn.character.age=age;newborn.currentYear=2026+age;processAnnualFinance(newborn);}verify(newborn.finances.cash===0,'supported childhood keeps personal cash at zero without ordinary annual charges');verify(newborn.finances.annualExpenses===0,'supported childhood reports zero personal annual expenses');verify(!newborn.finances.liabilities.some(l=>l.kind==='personal'),'supported childhood creates no hardship debt');
  const supportedAdult=createNewGame({seed:'supported-adult'});supportedAdult.character.age=22;supportedAdult.currentYear=2048;supportedAdult.flags.financialSupportChoiceMade=true;processAnnualFinance(supportedAdult);verify(supportedAdult.finances.annualExpenses===0,'adult who remains family-supported is not silently charged independent living costs');verify(!supportedAdult.finances.liabilities.some(l=>l.kind==='personal'),'family-supported adult does not create hardship debt from ordinary living costs');
  const transition=createNewGame({seed:'independence-transition'});transition.character.age=17;transition.currentYear=2043;const aged=ageUp(transition);verify(aged.success&&transition.character.age===18,'age-up reaches adulthood normally');verify(transition.pendingEvent?.eventId==='financial_independence_transition','adulthood presents an explicit financial-independence decision');verify(transition.finances.annualExpenses===0,'age 18 is not charged independent living costs before the player chooses independence');verify(resolvePendingEvent(transition,'stay_supported').success&&transition.flags.financiallyIndependent===false,'player can remain family-supported without forced independence');
  const independent=createNewGame({seed:'independent-costs'});independent.character.age=25;independent.currentYear=2051;independent.flags.financiallyIndependent=true;independent.finances.cash=0;processAnnualFinance(independent);const pressure=processDelayedEvents(independent);if(pressure)independent.pendingEvent=pressure;verify(independent.finances.annualExpenses>0,'financially independent adult receives ordinary annual costs');verify(independent.finances.liabilities.some(l=>l.kind==='personal'&&l.origin==='hardship'),'uncovered independent annual costs become labeled hardship debt');verify(independent.pendingEvent?.eventId==='financial_pressure_notice','new hardship debt surfaces a player-facing financial pressure event through scheduler arbitration');verify(independent.pendingEvent?.description.includes('hardship debt')===true,'financial pressure event explains where hardship debt came from');verify(independent.pendingEvent?.choices.some(c=>c.id==='carry')===true&&independent.pendingEvent.choices.some(c=>c.id==='review')===true,'financial pressure event preserves player choice instead of forcing a correction');
  for(let i=0;i<6;i++){independent.pendingEvent=undefined;processAnnualFinance(independent);}verify(Number(independent.flags.bankruptcies??0)===0,'repeated hardship never silently auto-files bankruptcy');
  independent.pendingEvent={eventId:'financial_pressure_notice',title:'Financial Pressure',description:'test',choices:[{id:'review',label:'Review bankruptcy options'}]};verify(resolvePendingEvent(independent,'review').success,'financial crisis choices resolve through the normal event engine');verify(independent.flags.bankruptcyReviewRequested===true,'bankruptcy review choice records player intent without filing automatically');
  const legacy=createNewGame({seed:'legacy-independence'});delete legacy.flags.financiallyIndependent;legacy.character.age=30;const migrated=migrateSave(legacy);verify(migrated.flags.financiallyIndependent===true,'legacy adult saves preserve prior independent-expense behavior when the new flag is absent');
  return checks;
}
