import type { GameState, Npc, Relationship } from '../types/game';
import { createNewGame } from '../systems/CharacterSystem';
import {
  MAX_ACTIVE_CONSEQUENCES,
  MAX_CONSEQUENCE_HISTORY,
  MAX_EVENT_COOLDOWNS,
  eventLastTriggeredAge,
  nextDueConsequence,
  recordEventTriggeredAge,
  scheduleConsequence,
} from '../systems/ConsequenceSystem';
import { eventEligibleForState, processDelayedEvents, resolvePendingEvent, triggerRandomEvent } from '../systems/EventSystem';
import { eventById, lifeEvents } from '../data/events';
import { migrateSave, exportSave, importSave } from '../services/SaveSystem';
import { validateState } from '../core/invariants';
import { captureRewindSnapshot } from '../systems/RewindSystem';
import { rewindToAge } from '../systems/AgingSystem';
import { processAnnualFinance } from '../systems/FinanceSystem';
import { continueAsChild } from '../systems/GenerationSystem';
import { ensureNpcLife } from '../systems/NpcLifeSystem';

function fail(message:string):never{throw new Error(message);}
function verify(condition:unknown,message:string):asserts condition{if(!condition)fail(message);}
function equal<T>(actual:T,expected:T,message:string){if(actual!==expected)fail(`${message} (expected ${String(expected)}, got ${String(actual)})`);}

function adult(seed:string,age=30){const state=createNewGame({seed,rewindEnabled:true});state.character.age=age;state.currentYear=state.character.birthYear+age;state.flags.financiallyIndependent=true;state.flags.financialSupportChoiceMade=true;return state;}
function scheduleKnown(state:GameState,id:string,priority:'low'|'normal'|'high'|'critical'='normal',dueAge=state.character.age){return scheduleConsequence(state,{id,eventId:'delayed_health_warning_return',dueAge,priority,dedupeKey:`test:${id}`,origin:{kind:'system',id:'phase7-regression',age:state.character.age}});}
function makeChild(state:GameState,id='phase7-child'):Npc{return{id,firstName:'Ari',lastName:state.character.lastName,age:20,alive:true,health:90,happiness:80,wealth:1000,countryId:state.character.countryId,city:state.character.city,sexuality:'bisexual',fertility:70,maritalStatus:'single',traits:['responsible'],hiddenOpinion:75,memories:[],parentIds:[state.character.id],childIds:[]};}

export function runPersistentConsequenceRegression(){
  let checks=0;const check=(condition:unknown,message:string)=>{verify(condition,message);checks+=1;};

  const fresh=createNewGame({seed:'phase7-fresh'});
  check(fresh.saveVersion===16,'01 new games must initialize the current save schema 16');
  check(fresh.consequenceScheduler?.version===1&&fresh.delayedEvents.length===0,'02 new games must initialize one empty scheduler authority');

  const cooldown=adult('phase7-cooldown');const refund=eventById['money_unexpected_refund_1'];verify(refund,'missing refund event fixture');
  const beforeProjection=JSON.stringify({rng:cooldown.rngCounter,id:cooldown.idCounter,scheduler:cooldown.consequenceScheduler});
  check(eventEligibleForState(cooldown,refund),'03 eligible event should be available before first exact-age cooldown record');
  equal(JSON.stringify({rng:cooldown.rngCounter,id:cooldown.idCounter,scheduler:cooldown.consequenceScheduler}),beforeProjection,'cooldown eligibility mutated state');checks+=1;
  recordEventTriggeredAge(cooldown,refund.id,30);cooldown.character.age=31;check(!eventEligibleForState(cooldown,refund),'05 cooldown should block age 31');cooldown.character.age=32;check(!eventEligibleForState(cooldown,refund),'06 cooldown should block through the exact cooldown age');cooldown.character.age=33;check(eventEligibleForState(cooldown,refund),'07 cooldown should expire at the first age beyond the exact window');

  const order=adult('phase7-order');scheduleKnown(order,'z-high','high');scheduleKnown(order,'a-high','high');scheduleKnown(order,'normal','normal');scheduleKnown(order,'critical','critical');
  check(nextDueConsequence(order)?.id==='critical','08 priority must outrank due-time ties');order.delayedEvents=order.delayedEvents.filter(item=>item.id!=='critical');check(nextDueConsequence(order)?.id==='a-high','09 deterministic ID tie-break must order same-priority same-age consequences');
  order.pendingEvent={eventId:'midlife_reassessment',title:'Existing',description:'Existing pending event',choices:[{id:'reflect',label:'Reflect'}]};const pendingBefore=JSON.stringify(order.pendingEvent);check(processDelayedEvents(order)===order.pendingEvent&&JSON.stringify(order.pendingEvent)===pendingBefore,'10 scheduler must never overwrite an unresolved pending event');order.pendingEvent=undefined;

  const windows=adult('phase7-window',25);const future=scheduleConsequence(windows,{id:'future-window',eventId:'delayed_health_warning_return',dueAge:27,earliestAge:27,latestAge:28,dedupeKey:'future-window'});check(future.scheduled&&!nextDueConsequence(windows),'11 consequence must not surface before earliest/due age');windows.character.age=29;check(!nextDueConsequence(windows)&&windows.consequenceScheduler.history.some(item=>item.id==='future-window'&&item.status==='cancelled'&&item.reason==='due_window_expired'),'12 expired due window must cancel deterministically into bounded history');

  const targets=adult('phase7-targets');const parentId=targets.relationships.find(rel=>rel.type==='parent')!.npcId;
  const targetResult=scheduleConsequence(targets,{id:'exact-target',eventId:'delayed_health_warning_return',dueAge:targets.character.age,payload:{npcId:parentId},targetRefs:[{kind:'npc',id:parentId}],validity:{targetMustExist:true,targetMustBeAlive:true,requiredRelationshipTypes:['parent']},dedupeKey:'exact-target'});verify(targetResult.consequence,'target consequence failed to schedule');const targetPending=processDelayedEvents(targets);check(targetPending?.payload?.npcId===parentId&&targetPending.consequence?.targetRefs?.[0]?.id===parentId,'13 exact NPC target must persist into the surfaced pending event');targets.pendingEvent=targetPending;const choice=targetPending?.choices[0];verify(choice,'target consequence missing a choice');resolvePendingEvent(targets,choice.id);check(targets.consequenceScheduler.history.some(item=>item.id==='exact-target'&&item.status==='completed'),'14 resolving a scheduled pending event must record completion history');

  const dead=adult('phase7-dead-target');const deadParent=dead.relationships.find(rel=>rel.type==='parent')!.npcId;dead.npcs[deadParent]!.alive=false;scheduleConsequence(dead,{id:'dead-target',eventId:'delayed_health_warning_return',dueAge:dead.character.age,targetRefs:[{kind:'npc',id:deadParent}],validity:{targetMustExist:true,targetMustBeAlive:true},dedupeKey:'dead-target'});check(!nextDueConsequence(dead)&&dead.consequenceScheduler.history.some(item=>item.id==='dead-target'&&item.reason==='target_npc_dead'),'15 dead exact target must cancel without retargeting');
  const wrongRel=adult('phase7-rel-target');const relParent=wrongRel.relationships.find(rel=>rel.type==='parent')!.npcId;scheduleConsequence(wrongRel,{id:'relationship-target',eventId:'delayed_health_warning_return',dueAge:wrongRel.character.age,targetRefs:[{kind:'npc',id:relParent}],validity:{targetMustExist:true,targetMustBeAlive:true,requiredRelationshipTypes:['friend']},dedupeKey:'relationship-target'});check(!nextDueConsequence(wrongRel)&&wrongRel.consequenceScheduler.history.some(item=>item.id==='relationship-target'&&item.reason==='required_relationship_missing'),'16 invalid relationship must cancel the exact target instead of silently retargeting');

  const dedupe=adult('phase7-dedupe');const first=scheduleKnown(dedupe,'dedupe-first');const idAfterFirst=dedupe.idCounter;const duplicate=scheduleConsequence(dedupe,{eventId:'delayed_health_warning_return',dueAge:dedupe.character.age,dedupeKey:'test:dedupe-first'});check(first.scheduled&&!duplicate.scheduled&&duplicate.reason==='duplicate'&&dedupe.idCounter===idAfterFirst,'17 dedupe rejection must be idempotent and consume no runtime ID');

  const bounded=adult('phase7-bounds');const rngBeforeBounds=bounded.rngCounter;for(let i=0;i<MAX_ACTIVE_CONSEQUENCES;i++)scheduleConsequence(bounded,{eventId:'delayed_health_warning_return',dueAge:90+i,dedupeKey:`bound-${i}`});const idBeforeReject=bounded.idCounter;const overflow=scheduleConsequence(bounded,{eventId:'delayed_health_warning_return',dueAge:999,dedupeKey:'bound-overflow'});check(bounded.delayedEvents.length===MAX_ACTIVE_CONSEQUENCES&&!overflow.scheduled&&overflow.reason==='queue_full'&&bounded.idCounter===idBeforeReject&&bounded.rngCounter===rngBeforeBounds,'18 active queue must stay bounded without consuming gameplay RNG or IDs on overflow');
  const history=adult('phase7-history');for(let i=0;i<MAX_CONSEQUENCE_HISTORY+12;i++){const result=scheduleConsequence(history,{id:`history-${String(i).padStart(3,'0')}`,eventId:'delayed_health_warning_return',dueAge:history.character.age,dedupeKey:`history-${i}`});verify(result.consequence,'history fixture failed');history.delayedEvents=[];history.consequenceScheduler.history.push({id:result.consequence.id,eventId:result.consequence.eventId,status:'completed',scheduledAge:history.character.age,dueAge:history.character.age,resolvedAge:history.character.age+i,priority:'normal'});}
  // Save migration owns durable normalization, including history retention bounds.
  const normalizedHistory=migrateSave(structuredClone(history));check(normalizedHistory.consequenceScheduler.history.length===MAX_CONSEQUENCE_HISTORY,'19 completion/cancellation history must remain bounded');
  const cooldownBound=adult('phase7-cooldown-bound');const rngBeforeCooldowns=cooldownBound.rngCounter;for(let i=0;i<MAX_EVENT_COOLDOWNS+9;i++)recordEventTriggeredAge(cooldownBound,`cooldown-${i}`,i);check(Object.keys(cooldownBound.consequenceScheduler.eventCooldownAges).length===MAX_EVENT_COOLDOWNS&&cooldownBound.rngCounter===rngBeforeCooldowns,'20 exact cooldown ledger must remain bounded and RNG-neutral');

  const legacy=adult('phase7-migration',40);legacy.saveVersion=12;const legacyParent=legacy.relationships.find(rel=>rel.type==='parent')!.npcId;legacy.delayedEvents=[{id:'legacy-delay',eventId:'delayed_health_warning_return',dueAge:42,payload:{npcId:legacyParent,originAge:39,requiredRelationshipTypes:['parent']}}];legacy.recentEventIds=['legacy-a','legacy-b','legacy-c'];legacy.pendingEvent={eventId:'midlife_reassessment',title:'Pending legacy event',description:'Keep me intact',choices:[{id:'reflect',label:'Reflect'}]};delete (legacy as Partial<GameState>).consequenceScheduler;const migrationRng=legacy.rngCounter,migrationId=legacy.idCounter;const migrated=migrateSave(structuredClone(legacy));
  check(migrated.saveVersion===16&&migrated.rngCounter===migrationRng&&migrated.idCounter===migrationId,'21 schema-12 migration through the current schema must be deterministic and RNG/ID neutral');
  const migratedDelay=migrated.delayedEvents.find(item=>item.id==='legacy-delay');check(migratedDelay?.targetRefs?.[0]?.id===legacyParent&&migratedDelay.origin?.age===39&&migratedDelay.validity?.requiredRelationshipTypes?.includes('parent')===true,'22 migration must preserve and normalize legacy delayed target/origin/relationship semantics');
  check(migrated.pendingEvent?.title==='Pending legacy event'&&eventLastTriggeredAge(migrated,'legacy-c')===40&&eventLastTriggeredAge(migrated,'legacy-a')===38,'23 migration must preserve pending event and deterministically reconstruct exact cooldown ages');
  const migratedAgain=migrateSave(structuredClone(migrated));check(JSON.stringify(migratedAgain.consequenceScheduler)===JSON.stringify(migrated.consequenceScheduler)&&JSON.stringify(migratedAgain.delayedEvents)===JSON.stringify(migrated.delayedEvents),'24 schema-13 normalization must be idempotent');
  const duplicateLegacy=adult('phase7-duplicate-migration',35);duplicateLegacy.saveVersion=12;delete (duplicateLegacy as Partial<GameState>).consequenceScheduler;duplicateLegacy.delayedEvents=[{id:'legacy-dup-a',eventId:'delayed_health_warning_return',dueAge:40,dedupeKey:'legacy-explicit-duplicate'},{id:'legacy-dup-b',eventId:'delayed_health_warning_return',dueAge:39,dedupeKey:'legacy-explicit-duplicate'}];const repairedDuplicate=migrateSave(duplicateLegacy);check(repairedDuplicate.delayedEvents.length===1&&repairedDuplicate.delayedEvents[0]?.id==='legacy-dup-b'&&repairedDuplicate.consequenceScheduler.history.some(item=>item.id==='legacy-dup-a'&&item.reason==='duplicate_normalized'),'25 explicitly duplicate delayed entries must collapse deterministically instead of making an old save invalid');
  const preservedLegacy=adult('phase7-legacy-preservation',35);preservedLegacy.saveVersion=12;delete (preservedLegacy as Partial<GameState>).consequenceScheduler;preservedLegacy.delayedEvents=[{id:'legacy-preserve-a',eventId:'delayed_health_warning_return',dueAge:39},{id:'legacy-preserve-b',eventId:'delayed_health_warning_return',dueAge:40}];const preservedMigrated=migrateSave(preservedLegacy);check(preservedMigrated.delayedEvents.length===2&&preservedMigrated.delayedEvents.some(item=>item.id==='legacy-preserve-a')&&preservedMigrated.delayedEvents.some(item=>item.id==='legacy-preserve-b'),'26 schema-12 migration must preserve distinct legacy delayed entries when the old save had no explicit dedupe authority');

  const roundTrip=adult('phase7-roundtrip');scheduleConsequence(roundTrip,{id:'roundtrip',eventId:'delayed_health_warning_return',dueAge:35,priority:'high',chainId:'roundtrip-chain',origin:{kind:'event',id:'origin-event',age:30},dedupeKey:'roundtrip-key'});recordEventTriggeredAge(roundTrip,'money_unexpected_refund_1',30);const imported=importSave(exportSave(roundTrip));check(JSON.stringify(imported.delayedEvents)===JSON.stringify(roundTrip.delayedEvents)&&JSON.stringify(imported.consequenceScheduler)===JSON.stringify(roundTrip.consequenceScheduler),'27 save export/import must round-trip scheduler metadata exactly');

  const rewind=adult('phase7-rewind',30);captureRewindSnapshot(rewind);scheduleConsequence(rewind,{id:'post-snapshot',eventId:'delayed_health_warning_return',dueAge:31,dedupeKey:'post-snapshot'});recordEventTriggeredAge(rewind,'post-snapshot-event',30);const rewindResult=rewindToAge(rewind,30);check(rewindResult.success&&!rewind.delayedEvents.some(item=>item.id==='post-snapshot')&&!('post-snapshot-event' in rewind.consequenceScheduler.eventCooldownAges),'28 rewind must restore the scheduler snapshot rather than leak future consequences/cooldowns backward');

  const finance=adult('phase7-finance',30);finance.finances.cash=0;scheduleConsequence(finance,{id:'priority-story',eventId:'delayed_health_warning_return',dueAge:30,priority:'high',dedupeKey:'priority-story'});processAnnualFinance(finance);check(!finance.pendingEvent&&finance.delayedEvents.some(item=>item.eventId==='financial_pressure_notice'),'29 Finance must request pressure through the scheduler and never seize pendingEvent directly');const picked=processDelayedEvents(finance);check(picked?.eventId==='delayed_health_warning_return'&&finance.delayedEvents.some(item=>item.eventId==='financial_pressure_notice'),'30 centralized scheduler priority must surface the higher-priority story while retaining Financial Pressure for the same-age backlog');

  const descendant=adult('phase7-descendant',48);const child=makeChild(descendant);descendant.npcs[child.id]=child;ensureNpcLife(descendant,child);const childRel:Relationship={id:'phase7-child-rel',npcId:child.id,type:'child',score:90,attraction:0,compatibility:70,yearsKnown:20};descendant.relationships.push(childRel);scheduleConsequence(descendant,{id:'old-life-consequence',eventId:'delayed_health_warning_return',dueAge:49,dedupeKey:'old-life'});recordEventTriggeredAge(descendant,'old-life-event',48);descendant.consequenceScheduler.history.push({id:'old-history',eventId:'delayed_health_warning_return',status:'completed',scheduledAge:47,dueAge:48,resolvedAge:48,priority:'normal'});descendant.character.alive=false;const continuation=continueAsChild(descendant,child.id);check(continuation.success&&descendant.delayedEvents.length===0&&descendant.pendingEvent===undefined&&descendant.consequenceScheduler.history.length===0&&Object.keys(descendant.consequenceScheduler.eventCooldownAges).length===0,'31 descendant continuation must not inherit the previous protagonist consequence queue/history/cooldowns');

  check(lifeEvents.length===691,'32 Phase 7A must not change the 691-event random library');
  check(validateState(fresh).length===0&&validateState(imported).length===0&&validateState(finance).length===0,'33 scheduler-enabled states must satisfy global invariants');

  const missingTarget=adult('phase7-missing-target',34);scheduleConsequence(missingTarget,{id:'missing-target',eventId:'delayed_health_warning_return',dueAge:34,targetRefs:[{kind:'npc',id:'missing-npc'}],validity:{targetMustExist:true},dedupeKey:'missing-target'});check(!nextDueConsequence(missingTarget)&&missingTarget.consequenceScheduler.history.some(item=>item.id==='missing-target'&&item.reason==='missing_target:npc'),'34 missing exact targets must cancel deterministically instead of retargeting');

  const oversizedLegacy=adult('phase7-oversized-import',35);oversizedLegacy.saveVersion=12;delete (oversizedLegacy as Partial<GameState>).consequenceScheduler;oversizedLegacy.delayedEvents=Array.from({length:100},(_,index)=>({id:`legacy-bound-${String(index).padStart(3,'0')}`,eventId:`legacy-bound-event-${index}`,dueAge:50+index,dedupeKey:`legacy-bound-key-${index}`}));const oversizedRng=oversizedLegacy.rngCounter,oversizedId=oversizedLegacy.idCounter;const repairedOversized=migrateSave(oversizedLegacy);check(repairedOversized.delayedEvents.length===MAX_ACTIVE_CONSEQUENCES&&repairedOversized.consequenceScheduler.history.filter(item=>item.reason==='queue_bound').length===4&&repairedOversized.rngCounter===oversizedRng&&repairedOversized.idCounter===oversizedId,'35 oversized legacy queues must prune deterministically to the active bound without consuming gameplay RNG or IDs');

  const rngA=adult('phase7-rng-parity',30);const rngB=structuredClone(rngA);const rngBeforeSchedule=rngB.rngCounter;scheduleConsequence(rngB,{id:'future-rng-neutral',eventId:'delayed_health_warning_return',dueAge:80,dedupeKey:'future-rng-neutral'});verify(rngB.rngCounter===rngBeforeSchedule,'scheduling a future consequence consumed gameplay RNG');const randomA=triggerRandomEvent(rngA);const randomB=triggerRandomEvent(rngB);
  // A future, non-due consequence may consume a runtime ID but must never perturb gameplay RNG or random-event selection.
  check(randomA?.eventId===randomB?.eventId&&randomA?.description===randomB?.description&&rngA.rngCounter===rngB.rngCounter,'36 future scheduled consequences must not perturb random-event RNG or selection');

  return checks;
}
