import { createNewGame } from '../systems/CharacterSystem';
import { addUnsecuredDebt, processAnnualFinance } from '../systems/FinanceSystem';
import { getPaymentObligations, payPaymentObligation, setPaymentAutoPay } from '../systems/PaymentSystem';
import { applyForPersonalLoan, fileVoluntaryBankruptcy, getBankruptcyDecision, getPersonalLoanOffers } from '../systems/PersonalBorrowingSystem';
import { migrateSave } from '../services/SaveSystem';

export function runPersonalBorrowingRegression(){let checks=0;const verify=(condition:unknown,message:string)=>{checks++;if(!condition)throw new Error(`Personal borrowing regression failed: ${message}`);};const adult=(seed:string)=>{const state=createNewGame({seed});state.character.age=30;state.currentYear=2056;state.finances.cash=5000;state.employment.current={jobId:'technology_2',title:'Engineer',company:'Test',startAge:25,salary:60000,performance:70,level:2};return state;};
  const browse=adult('loan-browse');const rng=browse.rngCounter;const ids=browse.idCounter;const first=JSON.stringify(getPersonalLoanOffers(browse));const second=JSON.stringify(getPersonalLoanOffers(browse));verify(first===second,'offer browsing is deterministic');verify(browse.rngCounter===rng&&browse.idCounter===ids,'offer browsing consumes no RNG or IDs');
  const offer=getPersonalLoanOffers(browse).find(item=>item.eligible);verify(Boolean(offer),'qualified adult receives at least one personal-loan offer');const amount=offer!.product.minAmount;const cash=browse.finances.cash;const applied=applyForPersonalLoan(browse,offer!.product.id,amount);verify(applied.success,'eligible personal-loan application succeeds');const loan=browse.finances.liabilities.find(item=>item.kind==='personal'&&item.origin==='borrowed');verify(Boolean(loan),'approved loan uses authoritative FinanceSystem liability');verify(browse.finances.cash===cash+amount,'approved principal becomes cash exactly once');verify(browse.finances.credit.inquiries.some(item=>item.productId===offer!.product.id&&item.outcome==='approved'),'approval records a formal shared credit inquiry');verify(loan?.autoPay===true,'new personal loan starts with annual auto-pay on');
  const bills=getPaymentObligations(browse);const bill=bills.find(item=>item.sourceId===loan!.id);verify(bill?.kind==='personal_loan','personal loan projects into centralized Bills & Payments');verify(Boolean(bill&&bill.dueNow>0),'personal loan exposes a real annual payment');
  const beforePay=browse.finances.cash;const paid=payPaymentObligation(browse,bill!.id);verify(paid.success,'personal-loan bill can be paid manually');verify(browse.finances.cash<beforePay,'manual loan payment spends cash');verify(loan?.prepaidThroughAge===browse.character.age+1,'manual payment is credited through next Age Up');
  const delinquent=adult('loan-delinquency');const dOffer=getPersonalLoanOffers(delinquent).find(item=>item.eligible)!;verify(applyForPersonalLoan(delinquent,dOffer.product.id,dOffer.product.minAmount).success,'delinquency fixture obtains loan');const dLoan=delinquent.finances.liabilities.find(item=>item.kind==='personal'&&item.origin==='borrowed')!;verify(setPaymentAutoPay(delinquent,`loan:${dLoan.id}`,false).success,'personal-loan auto-pay can be disabled centrally');processAnnualFinance(delinquent);verify(dLoan.delinquency?.status==='delinquent'&&dLoan.delinquency.arrears>0,'disabled auto-pay creates durable personal-loan delinquency');verify(delinquent.finances.credit.derogatories.some(item=>item.kind==='missed_payment'),'missed personal-loan payment reaches shared credit history');delinquent.finances.cash=100000;const cureBill=getPaymentObligations(delinquent).find(item=>item.sourceId===dLoan.id)!;verify(cureBill.status==='past_due','delinquent loan projects as past due');verify(payPaymentObligation(delinquent,cureBill.id).success,'past-due personal loan can be cured');verify(dLoan.delinquency?.status==='current','cure returns personal loan to current');
  const bankruptcy=adult('voluntary-bankruptcy');addUnsecuredDebt(bankruptcy,35000);bankruptcy.flags.cashShortfallYears=2;const secured={id:'mortgage-survives',kind:'mortgage' as const,principal:100000,balance:90000,annualRate:.05,annualPayment:7000,remainingYears:20};const student={id:'student-survives',kind:'student' as const,principal:12000,balance:9000,annualRate:.04,annualPayment:1500,remainingYears:6};bankruptcy.finances.liabilities.push(secured,student);const preview=getBankruptcyDecision(bankruptcy);verify(preview.eligible&&preview.dischargeableDebt>=35000,'serious distress unlocks voluntary bankruptcy with explicit dischargeable debt');verify(preview.securedDebt===90000&&preview.studentDebt===9000,'bankruptcy preview separates surviving debt');verify(fileVoluntaryBankruptcy(bankruptcy).success,'eligible player can voluntarily file bankruptcy');verify(!bankruptcy.finances.liabilities.some(item=>item.kind==='personal'),'bankruptcy discharges eligible personal debt');verify(bankruptcy.finances.liabilities.some(item=>item.id===secured.id)&&bankruptcy.finances.liabilities.some(item=>item.id===student.id),'bankruptcy preserves secured and student debt');verify(bankruptcy.finances.credit.derogatories.some(item=>item.kind==='bankruptcy'),'bankruptcy creates severe shared credit history');verify(Number(bankruptcy.flags.lastBankruptcyAge)===bankruptcy.character.age,'bankruptcy recovery clock persists');verify(!getBankruptcyDecision(bankruptcy).eligible,'repeat bankruptcy is blocked during recovery');
  const legacy=adult('loan-migration');legacy.saveVersion=12;legacy.finances.liabilities.push({id:'legacy-personal',kind:'personal',principal:2000,balance:1800,annualRate:.1,annualPayment:400,remainingYears:5});const migrated=migrateSave(legacy);const legacyLoan=migrated.finances.liabilities.find(item=>item.id==='legacy-personal')!;verify(migrated.saveVersion===12,'current-schema normalization preserves schema 12');verify(legacyLoan.autoPay===true&&legacyLoan.origin==='hardship','legacy personal debt migrates deterministically without losing balance');verify(legacyLoan.balance===1800,'migration preserves legacy personal-debt balance');
  return checks;
}
