import { actionUsesThisAge } from '../core/actionEconomy';
import { enforceStateInvariants, validateState } from '../core/invariants';
import { CURRENT_SAVE_VERSION } from '../core/saveVersion';
import { EVERTHREAD_CITY, EVERTHREAD_COUNTRY_ID } from '../data/countries';
import { RESIDENTIAL_LIFE_PLANS } from '../data/residentialLife';
import { sharedExperienceActivityById } from '../data/sharedExperiences';
import { exportSave, importSave } from '../services/SaveSystem';
import { rewindToAge } from '../systems/AgingSystem';
import { createNewGame } from '../systems/CharacterSystem';
import { continueAsChild, setEstateAssetBequest } from '../systems/GenerationSystem';
import { addNpcPropertyHolding, npcPropertyFromPlayerAsset, playerPropertyFromNpcHolding } from '../systems/NpcAssetSystem';
import { ensureNpcLife, relocateNpcHousehold, syncNpcHouseholdProjection } from '../systems/NpcLifeSystem';
import { buyProperty, rentOutProperty, sellProperty, setPrimaryResidence } from '../systems/PropertySystem';
import { captureRewindSnapshot } from '../systems/RewindSystem';
import { npcHouseholdMemberIds, npcHouseholdResidenceProjection, playerResidenceProjection, projectResidentialPlans, residentialPlanFor } from '../systems/ResidentialLifeSystem';
import { shareExperienceWithNpc, shareResidentialExperienceWithNpc } from '../systems/RelationshipSystem';
import type { GameState, Npc, PropertyAsset, Relationship, RelationshipType } from '../types/game';
import type { NpcPropertyHolding } from '../types/npcAssets';

function clone<T>(value:T):T{return structuredClone(value);}
function residentialState(seed:string,age=28){
  const state=createNewGame({seed});state.seed=seed;state.character.age=age;state.currentYear=2070;state.settings.autoSave=false;
  state.character.countryId=EVERTHREAD_COUNTRY_ID;state.character.city=EVERTHREAD_CITY;state.character.stats.health=95;state.character.stats.happiness=95;
  state.finances.cash=2_000_000;state.flags.financiallyIndependent=true;state.flags.financialSupportChoiceMade=true;return state;
}
function addNpc(state:GameState,id:string,type:RelationshipType='friend',age=state.character.age){
  const npc:Npc={id,firstName:'Morgan',lastName:'Thread',age,alive:true,health:95,happiness:95,wealth:40_000,countryId:EVERTHREAD_COUNTRY_ID,city:EVERTHREAD_CITY,sexuality:'pansexual',fertility:70,maritalStatus:'single',traits:['loyal','playful'],hiddenOpinion:100,memories:[],parentIds:[],childIds:[],simulationTier:'full',preferences:{version:1,likes:['home','cozy','social','family'],dislikes:[],aversions:[]}};
  const rel:Relationship={id:`rel-${id}`,npcId:id,type,score:100,attraction:40,compatibility:100,yearsKnown:6};state.npcs[id]=npc;state.relationships.push(rel);ensureNpcLife(state,npc);npc.assetPortfolio={properties:[],businesses:[]};syncNpcHouseholdProjection(state,npc);return{npc,rel};
}
function npcProperty(npc:Npc,id:string,name='Cottage',options:Partial<NpcPropertyHolding>={}):NpcPropertyHolding{
  return{id,typeId:'starter_house_standard',name,location:npc.city,purchasePrice:120_000,marketValue:140_000,mortgageBalance:20_000,condition:88,propertyAge:7,acquiredAge:Math.max(18,npc.age-7),origin:'purchased',...options};
}
function playerProperty(state:GameState,id:string,name:string,options:Partial<PropertyAsset>={}):PropertyAsset{
  const property:PropertyAsset={id,typeId:'starter_house_standard',name,location:state.character.city,purchasePrice:150_000,marketValue:170_000,condition:90,age:5,amenities:['yard'],origin:'purchased',...options};state.assets.properties.push(property);return property;
}
function addChild(state:GameState,id:string,age=30){const pair=addNpc(state,id,'child',age);pair.npc.parentIds=[state.character.id];pair.rel.yearsKnown=age;return pair;}
function advanceYear(state:GameState){state.character.age+=1;state.currentYear+=1;for(const npc of Object.values(state.npcs))if(npc.alive)npc.age+=1;}

export function runPhase10AResidentialLifeRegression(){
  let checks=0;function verify(condition:unknown,message:string):asserts condition{checks+=1;if(!condition)throw new Error(`Phase 10A residential-life regression failed: ${message}`);}

  verify(CURRENT_SAVE_VERSION===17,'01 Residential Life must remain backward-compatible with schema 17 instead of creating required top-level state');
  verify(RESIDENTIAL_LIFE_PLANS.length===5&&new Set(RESIDENTIAL_LIFE_PLANS.map(plan=>plan.id)).size===5,'02 Residential Life must have five unique authored plans');
  verify(RESIDENTIAL_LIFE_PLANS.every(plan=>Boolean(sharedExperienceActivityById[plan.activityId])&&sharedExperienceActivityById[plan.activityId].placeIds.includes('threadwell-residential')),'03 every residential plan must reuse a certified Phase 9 shared activity at Threadwell rather than fork an outcome engine');
  const fresh=residentialState('10a-fresh');
  verify(!('residenceState' in (fresh as unknown as Record<string,unknown>))&&!('householdLedger' in (fresh as unknown as Record<string,unknown>)),'04 GameState must contain no parallel residence or household ledger');
  verify(playerResidenceProjection(fresh).kind==='rented'&&playerResidenceProjection(fresh).visitable,'05 an independent Everthread adult without owned property projects a visitable rented home');
  const minor=residentialState('10a-minor',15);minor.flags.financiallyIndependent=false;verify(playerResidenceProjection(minor).kind==='family','06 a dependent minor projects the existing family-home context without inventing property ownership');
  const incarcerated=residentialState('10a-incarcerated');incarcerated.legal.sentenceRemaining=2;verify(playerResidenceProjection(incarcerated).kind==='institutional'&&!playerResidenceProjection(incarcerated).visitable,'07 incarceration projects institutional residence and blocks home visits');

  const purchase=residentialState('10a-purchase');
  verify(buyProperty(purchase,'starter_house_standard',false).success,'08 an adult with sufficient cash can still purchase a property through PropertySystem');
  const first=purchase.assets.properties.at(-1)!;verify(first.origin==='purchased'&&first.primaryResidence===true&&playerResidenceProjection(purchase).propertyId===first.id,'09 the first local non-rental purchase becomes the projected home inside the existing property authority');
  verify(buyProperty(purchase,'starter_house_value',false).success,'10 a second property purchase remains supported');const second=purchase.assets.properties.at(-1)!;
  verify(purchase.assets.properties.find(property=>property.id===second.id)?.primaryResidence!==true&&playerResidenceProjection(purchase).propertyId===first.id,'11 buying a second property must not silently steal the current-home designation');
  const browseBefore=JSON.stringify(purchase),browseRng=purchase.rngCounter,browseId=purchase.idCounter;playerResidenceProjection(purchase);
  verify(JSON.stringify(purchase)===browseBefore&&purchase.rngCounter===browseRng&&purchase.idCounter===browseId,'12 player residence projection is strictly read-only and consumes no gameplay RNG/runtime IDs');
  verify(setPrimaryResidence(purchase,second.id).success&&purchase.assets.properties.find(property=>property.id===second.id)?.primaryResidence===true&&purchase.assets.properties.find(property=>property.id===first.id)?.primaryResidence!==true&&playerResidenceProjection(purchase).propertyId===second.id,'13 Make home switches the exact property and clears the previous designation');
  second.rental={annualRent:10_000,reliability:60,occupied:false};verify(setPrimaryResidence(purchase,second.id).success&&!purchase.assets.properties.find(property=>property.id===second.id)?.rental&&purchase.assets.properties.find(property=>property.id===second.id)?.primaryResidence===true,'14 moving into a vacant listed property explicitly removes it from the rental market');
  first.rental={annualRent:10_000,reliability:60,occupied:true};const occupiedBefore=JSON.stringify(purchase);verify(!setPrimaryResidence(purchase,first.id).success&&JSON.stringify(purchase)===occupiedBefore,'15 an occupied tenant blocks moving in without mutating the property or tenancy');
  verify(rentOutProperty(purchase,second.id).success&&purchase.assets.properties.find(property=>property.id===second.id)?.primaryResidence!==true&&Boolean(purchase.assets.properties.find(property=>property.id===second.id)?.rental),'16 renting out the current home explicitly moves the player out instead of allowing one property to be both home and rental');
  verify(playerResidenceProjection(purchase).kind==='rented','17 if every local owned property is rented, residence falls back to the existing non-owned rented-home projection');
  delete first.rental;verify(setPrimaryResidence(purchase,first.id).success&&sellProperty(purchase,first.id).success&&playerResidenceProjection(purchase).propertyId===undefined,'18 selling the designated home cannot leave a dangling current-home reference');
  const remote=residentialState('10a-remote');playerProperty(remote,'remote-home','Remote House',{location:'Tulsa',primaryResidence:true});verify(playerResidenceProjection(remote).kind==='rented'&&playerResidenceProjection(remote).propertyId===undefined,'19 an owned property in another city is not projected as the player current residence');

  const provenance=residentialState('10a-provenance');const legacyProperty=playerProperty(provenance,'legacy-home','Legacy House',{origin:undefined,primaryResidence:true});const inherited=playerProperty(provenance,'inherited-home','Grandmother House',{origin:'inherited',inheritedFromNpcId:'grandma'});const rentalPrimary=playerProperty(provenance,'bad-rental','Rental House',{primaryResidence:true,rental:{annualRent:12_000,reliability:60,occupied:false}});enforceStateInvariants(provenance);
  verify(legacyProperty.origin==='purchased','20 legacy player properties deterministically normalize missing provenance to purchased');
  verify(provenance.assets.properties.filter(property=>property.primaryResidence).length===1&&!rentalPrimary.primaryResidence,'21 invariant repair keeps at most one player home and forbids a rental from also being primary');
  verify(inherited.origin==='inherited'&&inherited.inheritedFromNpcId==='grandma','22 valid inherited-home provenance survives invariant repair even if the ancestor is historical rather than a live NPC');
  const inheritanceView=playerResidenceProjection({...provenance,assets:{...provenance.assets,properties:[{...inherited,primaryResidence:true}]}});
  verify(inheritanceView.familyLandmark&&inheritanceView.detail.includes('Inherited family home'),'23 inherited player property projects as a recognizable family landmark');

  const npcOwned=residentialState('10a-npc-owned');const ownedPair=addNpc(npcOwned,'owned-friend');addNpcPropertyHolding(npcOwned,ownedPair.npc,npcProperty(ownedPair.npc,'npc-cottage','Cottage',{primaryResidence:true}));const ownedView=npcHouseholdResidenceProjection(npcOwned,ownedPair.npc.id)!;
  verify(ownedView.residence.kind==='owned'&&ownedView.residence.propertyId==='npc-cottage'&&ownedView.residence.label.includes('Cottage'),'24 an NPC current home projects from the exact NPC property holding');
  const household=residentialState('10a-household');const partnerA=addNpc(household,'partner-a');const partnerB=addNpc(household,'partner-b','friend');partnerA.npc.partnerId=partnerB.npc.id;partnerB.npc.partnerId=partnerA.npc.id;addNpcPropertyHolding(household,partnerB.npc,npcProperty(partnerB.npc,'partner-home','Shared House',{primaryResidence:true}));
  const sharedView=npcHouseholdResidenceProjection(household,partnerA.npc.id)!;verify(sharedView.residence.kind==='shared'&&sharedView.residence.ownerNpcId===partnerB.npc.id&&sharedView.memberIds.includes(partnerB.npc.id),'25 an adult household can resolve the partner-owned home without duplicating ownership');
  const playerParent=residentialState('10a-player-parent');const parentHome=playerProperty(playerParent,'player-family-home','Family House',{primaryResidence:true});const child=addNpc(playerParent,'minor-child','child',10);child.npc.parentIds=[playerParent.character.id];const childHome=npcHouseholdResidenceProjection(playerParent,child.npc.id)!;
  verify(childHome.residence.kind==='family'&&childHome.residence.propertyId===parentHome.id&&childHome.residence.label.includes(child.npc.firstName),'26 a minor NPC child linked to the protagonist projects the player actual home as their family household');
  const householdMembers=npcHouseholdMemberIds(household,partnerA.npc.id);verify(householdMembers.includes(partnerA.npc.id)&&householdMembers.includes(partnerB.npc.id),'27 household membership projection includes the exact partnered adults');
  const inheritedNpc=residentialState('10a-npc-inherited');const inheritedPair=addNpc(inheritedNpc,'inherited-relative','sibling');addNpcPropertyHolding(inheritedNpc,inheritedPair.npc,npcProperty(inheritedPair.npc,'heir-home','Willow Home',{origin:'inherited',inheritedFromNpcId:'ancestor',primaryResidence:true}));
  verify(npcHouseholdResidenceProjection(inheritedNpc,inheritedPair.npc.id)!.residence.familyLandmark,'28 an inherited NPC home remains recognizable as a family landmark');
  inheritedPair.npc.imprisoned=true;ensureNpcLife(inheritedNpc,inheritedPair.npc).legal.sentenceRemaining=1;verify(!npcHouseholdResidenceProjection(inheritedNpc,inheritedPair.npc.id)!.residence.visitable,'29 an incarcerated NPC household is not visitable');
  inheritedPair.npc.imprisoned=false;inheritedPair.npc.life!.legal.sentenceRemaining=0;inheritedPair.npc.alive=false;verify(!npcHouseholdResidenceProjection(inheritedNpc,inheritedPair.npc.id)!.residence.visitable,'30 a deceased NPC former residence cannot be treated as an ordinary social visit');

  const relocate=residentialState('10a-relocate');const relocatePair=addNpc(relocate,'moving-friend');const moveHolding=npcProperty(relocatePair.npc,'move-home','Old Home',{primaryResidence:true});addNpcPropertyHolding(relocate,relocatePair.npc,moveHolding);const moved=relocateNpcHousehold(relocate,relocatePair.npc.id,'Tulsa');
  verify(moved.includes(relocatePair.npc.id)&&relocatePair.npc.assetPortfolio!.properties.some(property=>property.id==='move-home')&&!relocatePair.npc.assetPortfolio!.properties[0]!.primaryResidence,'31 household relocation preserves property ownership but clears a stale remote-home designation');
  const npcRepair=residentialState('10a-npc-repair');const repairPair=addNpc(npcRepair,'repair-npc');repairPair.npc.assetPortfolio={properties:[npcProperty(repairPair.npc,'repair-a','A',{primaryResidence:true}),npcProperty(repairPair.npc,'repair-b','B',{primaryResidence:true}),npcProperty(repairPair.npc,'repair-remote','Remote',{location:'Tulsa',primaryResidence:true})],businesses:[]};repairPair.npc.inheritanceTrust={releaseAge:18,value:100_000,liquidValue:0,properties:[npcProperty(repairPair.npc,'trust-home','Trust Home',{primaryResidence:true,origin:'inherited'})],businesses:[]};enforceStateInvariants(npcRepair);
  verify(repairPair.npc.assetPortfolio!.properties.filter(property=>property.primaryResidence).length===1&&!repairPair.npc.assetPortfolio!.properties.find(property=>property.id==='repair-remote')!.primaryResidence,'32 NPC invariant repair keeps only one local current-home designation');
  verify(!repairPair.npc.inheritanceTrust!.properties![0]!.primaryResidence,'33 property held in an inheritance trust cannot simultaneously be an occupied current home');

  const friendPlansState=residentialState('10a-plans');const friendPair=addNpc(friendPlansState,'plan-friend','best_friend');addNpcPropertyHolding(friendPlansState,friendPair.npc,npcProperty(friendPair.npc,'plan-home','Lantern House',{primaryResidence:true}));const planBefore=JSON.stringify(friendPlansState),planRng=friendPlansState.rngCounter,planIdCounter=friendPlansState.idCounter;const friendPlans=projectResidentialPlans(friendPlansState,friendPair.npc.id);
  verify(friendPlans.map(plan=>plan.id).sort().join(',')==='cook-at-home,invite-home,visit-their-home','34 adult best friends project exactly the age-appropriate residential plans');
  verify(friendPlans.some(plan=>plan.id==='visit-their-home'&&plan.residence.propertyId==='plan-home'&&plan.residenceLabel.includes('Lantern House')),'35 Visit their home binds to the exact NPC residence rather than a generic fake location');
  verify(JSON.stringify(friendPlansState)===planBefore&&friendPlansState.rngCounter===planRng&&friendPlansState.idCounter===planIdCounter,'36 residential plan browsing is strictly read-only, RNG-neutral, and runtime-ID neutral');
  const familyPlansState=residentialState('10a-family-plans');const familyPair=addNpc(familyPlansState,'plan-sibling','sibling');const familyPlans=projectResidentialPlans(familyPlansState,familyPair.npc.id);
  verify(familyPlans.some(plan=>plan.id==='family-visit')&&!familyPlans.some(plan=>plan.id==='visit-their-home'),'37 family relationships receive the family visit instead of the generic non-family home visit');
  const youthPlansState=residentialState('10a-youth-plans',12);youthPlansState.flags.financiallyIndependent=false;const youthPair=addNpc(youthPlansState,'youth-friend','friend',12);const youthResidential=projectResidentialPlans(youthPlansState,youthPair.npc.id);
  verify(youthResidential.some(plan=>plan.id==='sleepover-at-home')&&youthResidential.some(plan=>plan.id==='cook-at-home'),'38 children can project age-appropriate sleepover/cooking plans against actual residential context');
  youthPlansState.character.age=18;youthPair.npc.age=18;verify(!projectResidentialPlans(youthPlansState,youthPair.npc.id).some(plan=>plan.id==='sleepover-at-home'),'39 residential sleepovers remain bounded to the certified childhood/teen age range');
  const coworkerState=residentialState('10a-coworker');const coworker=addNpc(coworkerState,'coworker-only','coworker');verify(projectResidentialPlans(coworkerState,coworker.npc.id).length===0,'40 ordinary coworkers do not gain residential intimacy merely from a workplace relationship');
  const estrangedState=residentialState('10a-estranged');const estranged=addNpc(estrangedState,'estranged-friend','friend');estranged.rel.estranged=true;verify(projectResidentialPlans(estrangedState,estranged.npc.id).length===0,'41 estranged relationships cannot project residential social plans');
  const remotePlans=residentialState('10a-remote-plans');const remotePair=addNpc(remotePlans,'remote-friend','friend');remotePair.npc.city='Tulsa';const remoteOptions=projectResidentialPlans(remotePlans,remotePair.npc.id);verify(remoteOptions.length>0&&remoteOptions.every(plan=>!plan.allowed),'42 a remote friend remains visible as residential context but every home visit is explicitly disabled');

  const commit=residentialState('10a-commit');const commitPair=addNpc(commit,'commit-friend','best_friend');addNpcPropertyHolding(commit,commitPair.npc,npcProperty(commitPair.npc,'commit-home','Cottage',{primaryResidence:true}));const beforeScore=commitPair.rel.score,beforeOpinion=commitPair.npc.hiddenOpinion,beforeHappiness=commit.character.stats.happiness,beforeRng=commit.rngCounter,beforeTimeline=commit.timeline.length;
  const committed=shareResidentialExperienceWithNpc(commit,commitPair.npc.id,'visit-their-home');
  verify(committed.success&&Boolean(committed.experience),'43 a valid home visit commits through the real shared-experience action path');
  verify(committed.experience!.placeLabel.includes('Cottage')&&committed.experience!.activityLabel==='Visit their home'&&!committed.experience!.prose.includes('Threadwell Residential'),'44 committed residential prose/result exposes the actual residence label rather than pretending the outing happened at a generic neighborhood');
  verify(commit.rngCounter===beforeRng+1&&commit.timeline.length===beforeTimeline+1,'45 a committed residential experience consumes exactly one shared-experience RNG draw and one timeline consequence');
  verify(commitPair.rel.score>=beforeScore&&commitPair.npc.hiddenOpinion>=beforeOpinion&&commit.character.stats.happiness>=beforeHappiness,'46 residential outcomes mutate the same relationship/opinion/happiness authorities as other Phase 9 experiences');
  verify(actionUsesThisAge(commit,'social.npc.total',commitPair.npc.id)===1&&actionUsesThisAge(commit,'social.npc.action',`${commitPair.npc.id}:residential:visit-their-home`)===1,'47 residential visits consume the established per-person social budget plus one exact residential action key');
  verify(commitPair.npc.memories.some(memory=>memory.kind.startsWith('residential:visit-their-home:commit-home')),'48 meaningful home visits write through the existing bounded NPC memory ledger with exact-home identity');
  const blockedRng=commit.rngCounter,blockedTimeline=commit.timeline.length,blockedState=JSON.stringify(commit);const blocked=shareResidentialExperienceWithNpc(commit,commitPair.npc.id,'visit-their-home');
  verify(!blocked.success&&commit.rngCounter===blockedRng&&commit.timeline.length===blockedTimeline&&JSON.stringify(commit)===blockedState,'49 repeating the same residential plan in one age is blocked without hidden mutation or RNG consumption');
  verify(shareResidentialExperienceWithNpc(commit,commitPair.npc.id,'invite-home').success&&shareResidentialExperienceWithNpc(commit,commitPair.npc.id,'cook-at-home').success&&actionUsesThisAge(commit,'social.npc.total',commitPair.npc.id)===3,'50 distinct residential plans can fill—but never bypass—the existing three-per-person social budget');
  const fourthRng=commit.rngCounter;verify(!shareExperienceWithNpc(commit,commitPair.npc.id,'nightjar-diner','diner_meal').success&&commit.rngCounter===fourthRng,'51 a fourth generic outing is blocked by the same shared social budget after three residential interactions');
  const invalid=residentialState('10a-invalid');const invalidPair=addNpc(invalid,'invalid-friend');const invalidBefore=JSON.stringify(invalid);verify(!shareResidentialExperienceWithNpc(invalid,invalidPair.npc.id,'not-a-plan').success&&JSON.stringify(invalid)===invalidBefore,'52 invalid residential plan ids fail mutation-neutral');
  invalidPair.npc.alive=false;const deadBefore=JSON.stringify(invalid);verify(!shareResidentialExperienceWithNpc(invalid,invalidPair.npc.id,'visit-their-home').success&&JSON.stringify(invalid)===deadBefore,'53 deceased residential targets fail safely without state mutation');

  const conversion=residentialState('10a-conversion');const conversionNpc=addNpc(conversion,'conversion-heir','child',35).npc;const source=playerProperty(conversion,'conversion-home','Conversion Home',{origin:'purchased',primaryResidence:true});const npcHolding=npcPropertyFromPlayerAsset(conversion,conversionNpc,source,undefined,conversion.character.id);verify(npcHolding.origin==='inherited'&&npcHolding.inheritedFromNpcId===conversion.character.id&&!npcHolding.primaryResidence,'54 player-to-NPC inheritance preserves exact property provenance without inheriting the deceased household current-home flag');
  npcHolding.primaryResidence=true;const convertedBack=playerPropertyFromNpcHolding(conversion,npcHolding).property;verify(convertedBack.origin==='inherited'&&convertedBack.inheritedFromNpcId===conversion.character.id&&convertedBack.primaryResidence===true,'55 NPC-to-player conversion preserves inherited-family provenance and a valid successor own-home designation');

  const dynasty=residentialState('10a-dynasty',62);dynasty.finances.cash=1_000_000;const heir=addChild(dynasty,'residential-heir',32);heir.npc.wealth=20_000;addNpcPropertyHolding(dynasty,heir.npc,npcProperty(heir.npc,'heir-own-home','Heir House',{primaryResidence:true}));const priorPlayerId=dynasty.character.id;const parentEstateHome=playerProperty(dynasty,'parent-estate-home','Thread Family Home',{primaryResidence:true});setEstateAssetBequest(dynasty,'property',parentEstateHome.id,heir.npc.id);dynasty.character.alive=false;
  verify(continueAsChild(dynasty,heir.npc.id).success,'56 descendant continuation succeeds with both an existing successor home and an inherited parent home');
  const ownAfter=dynasty.assets.properties.find(property=>property.id==='heir-own-home')!,inheritedAfter=dynasty.assets.properties.find(property=>property.id==='parent-estate-home')!;
  verify(ownAfter.primaryResidence===true&&playerResidenceProjection(dynasty).propertyId===ownAfter.id,'57 descendant continuation preserves the successor existing biography/home instead of replacing it with the parent estate');
  verify(inheritedAfter.origin==='inherited'&&inheritedAfter.inheritedFromNpcId===priorPlayerId&&!inheritedAfter.primaryResidence&&playerResidenceProjection({...dynasty,assets:{...dynasty.assets,properties:[{...inheritedAfter,primaryResidence:true}]}}).familyLandmark,'58 inherited parent property remains a recognizable family landmark without hijacking the successor current home');

  const saved=residentialState('10a-save');const savedHome=playerProperty(saved,'saved-home','Saved Home',{origin:'inherited',inheritedFromNpcId:'historic-parent',primaryResidence:true});const savedFriend=addNpc(saved,'saved-friend');addNpcPropertyHolding(saved,savedFriend.npc,npcProperty(savedFriend.npc,'saved-npc-home','Saved NPC Home',{origin:'inherited',inheritedFromNpcId:'npc-ancestor',primaryResidence:true}));const roundTrip=importSave(exportSave(saved));
  verify(roundTrip.saveVersion===17&&roundTrip.assets.properties.find(property=>property.id===savedHome.id)?.primaryResidence===true&&roundTrip.assets.properties.find(property=>property.id===savedHome.id)?.origin==='inherited','59 schema-17 save/load preserves optional player home/provenance metadata');
  verify(roundTrip.npcs[savedFriend.npc.id]?.assetPortfolio?.properties[0]?.primaryResidence===true&&roundTrip.npcs[savedFriend.npc.id]?.assetPortfolio?.properties[0]?.origin==='inherited','60 schema-17 save/load preserves optional NPC household-home/provenance metadata');
  verify(exportSave(importSave(exportSave(roundTrip)))===exportSave(roundTrip),'61 once normalized, repeated schema-17 save/load cycles are idempotent with Residential Life metadata');
  const oldSave=residentialState('10a-old-save');const oldAsset=playerProperty(oldSave,'old-home','Old Save Home',{origin:undefined,primaryResidence:undefined});const oldJson=exportSave(oldSave);const oldLoaded=importSave(oldJson);verify(oldLoaded.saveVersion===17&&oldLoaded.assets.properties.find(property=>property.id===oldAsset.id)?.origin==='purchased','62 current-schema legacy property records lacking 10A optional fields normalize deterministically without a schema bump');

  const rewind=residentialState('10a-rewind',30);rewind.flags.rewindEnabled=true;const rewindA=playerProperty(rewind,'rewind-a','First Home',{primaryResidence:true});const rewindB=playerProperty(rewind,'rewind-b','Second Home');const rewindFriend=addNpc(rewind,'rewind-friend');captureRewindSnapshot(rewind);advanceYear(rewind);verify(setPrimaryResidence(rewind,rewindB.id).success&&shareResidentialExperienceWithNpc(rewind,rewindFriend.npc.id,'invite-home').success,'63 residential designation and visit consequences can occur after a valid rewind snapshot');
  verify(rewindToAge(rewind,30).success&&rewind.assets.properties.find(property=>property.id===rewindA.id)?.primaryResidence===true&&!rewind.assets.properties.find(property=>property.id===rewindB.id)?.primaryResidence,'64 rewind atomically restores the prior current-home designation');
  verify(actionUsesThisAge(rewind,'social.npc.total',rewindFriend.npc.id)===0&&rewind.npcs[rewindFriend.npc.id]?.memories.every(memory=>!memory.kind.startsWith('residential:')),'65 rewind also restores the residential social action/memory consequences through existing rewind authority');

  verify(validateState(enforceStateInvariants(dynasty)).length===0&&validateState(enforceStateInvariants(roundTrip)).length===0&&validateState(enforceStateInvariants(rewind)).length===0,'66 Residential Life states remain clean under canonical invariants across dynasty/save/rewind paths');

  const minorInheritance=residentialState('10a-minor-inheritance',16);minorInheritance.flags.financiallyIndependent=false;const minorHome=playerProperty(minorInheritance,'minor-inherited-home','Inherited Cottage',{origin:'inherited',inheritedFromNpcId:'late-parent',primaryResidence:true});
  verify(!setPrimaryResidence(minorInheritance,minorHome.id).success&&playerResidenceProjection(minorInheritance).kind==='family'&&playerResidenceProjection(minorInheritance).propertyId===undefined,'67 a minor can own inherited property without self-designating or projecting it as an independent residence');
  enforceStateInvariants(minorInheritance);verify(!minorHome.primaryResidence&&minorHome.origin==='inherited'&&minorHome.inheritedFromNpcId==='late-parent'&&validateState(minorInheritance).length===0,'68 invariant repair strips a stale minor primary-home role while preserving exact inherited ownership/provenance');

  const sharedPlayerHome=residentialState('10a-player-partner-home');const exactPlayerHome=playerProperty(sharedPlayerHome,'player-partner-home','Juniper House',{primaryResidence:true});const currentPartner=addNpc(sharedPlayerHome,'current-player-partner','partner');const partnerResidence=npcHouseholdResidenceProjection(sharedPlayerHome,currentPartner.npc.id)!;
  verify(partnerResidence.residence.kind==='shared'&&partnerResidence.residence.propertyId===exactPlayerHome.id&&partnerResidence.residence.label.includes(currentPartner.npc.firstName),'69 a current player partner without their own residence projects the player exact home as the shared household');
  return checks;
}
