import { createNewGame } from '../systems/CharacterSystem';
import { activeSpecialCareerWorld, archiveSpecialCareerWorld, ensureSpecialCareerWorld, specialCareerWorlds } from '../systems/SpecialCareerWorldSystem';
import { ensureSpecialCareerRelationships } from '../systems/SpecialCareerRelationshipSystem';
import { createRng } from '../core/rng';
import { processAnnualFinance } from '../systems/FinanceSystem';
import {
  beginRacingSeason,
  expireRacingContractOffer,
  joinRacingPath,
  processRacingCareerYear,
  racingContractDecision,
  racingContractOffer,
  racingSeasonHistory,
  retireRacingCareer,
  seekRacingContract,
  trainRacing,
} from '../systems/RacingCareerCycleSystem';

export function runRacingCareerRegression(){
  let checks=0;
  function verify(condition:unknown,message:string):asserts condition {checks+=1;if(!condition)throw new Error(`Racing-career regression failed: ${message}`);}
  const metrics={momentum:82,chemistry:74,rivalry:22,prestige:76};

  const readOnly=createNewGame({seed:'phase4d5-racing-readonly'});
  verify(racingSeasonHistory(readOnly).length===0,'reading empty racing history must return an empty projection');
  verify(racingContractOffer(readOnly)===undefined,'reading an empty racing contract offer must return undefined');
  verify(readOnly.specialCareers.racing===undefined,'read-only racing projections must not create career state');

  const entry=createNewGame({seed:'phase4d5-racing-entry'});entry.character.age=16;entry.currentYear=2036;entry.character.secondary.athleticism=78;
  const joined=joinRacingPath(entry);verify(joined.success,'an eligible teen must be able to enter the racing pathway');
  const entryWorld=activeSpecialCareerWorld(entry,'racing');verify(Boolean(entryWorld),'joining racing must create a persistent team world');
  const entryRacing=entry.specialCareers.racing as Record<string,number|string|boolean>;
  verify(entryRacing.racingPathway===true&&entryRacing.contractActive===true,'joining racing must create a real contracted pathway');
  verify(Number(entryRacing.contractRemaining)>=2&&Number(entryRacing.contractRemaining)<=3,'entry racing contracts must use a bounded multi-year term');
  verify(Number(entryRacing.salary)>0,'entry racing contracts must preserve per-season salary');
  verify(Number(entryRacing.seasons)===0,'new racing careers must begin with zero completed seasons');
  verify(Number(entryRacing.teamsPlayedFor)===1,'the first racing team must be counted exactly once');
  const entryNpcIds=entryWorld!.members.map(member=>member.npcId).join('|');
  verify(entry.relationships.length>0,'the persistent racing team must initialize real NPC relationships');
  verify(!joinRacingPath(entry).success,'joining again must not create a duplicate racing career');
  verify(specialCareerWorlds(entry,'racing').length===1,'duplicate join attempts must not create another team world');

  entry.actionLedger.age=16;entry.actionLedger.uses={};
  const trained=trainRacing(entry);verify(trained.success,'contracted racers must be able to train');verify(Number(entryRacing.skill)>0,'racing training must preserve skill progression');
  const season=beginRacingSeason(entry,88);verify(season.success,'a contracted racer must be able to enter one season per age');
  verify(entryRacing.seasonActive===true,'the Race action must start a season period instead of resolving an isolated event immediately');
  verify(Number(entryRacing.currentSeasonRaces)>=18&&Number(entryRacing.currentSeasonRaces)<=24,'racing seasons must contain a bounded multi-round schedule');
  const raceUsesBefore=entry.actionLedger.uses['special.race']??0;const overlap=beginRacingSeason(entry,90);verify(!overlap.success,'an active season must block overlapping racing seasons');verify((entry.actionLedger.uses['special.race']??0)===raceUsesBefore,'overlap blocking must happen before another racing opportunity is consumed');

  const termBefore=Number(entryRacing.contractRemaining);entry.character.age=17;entry.currentYear=2037;
  processRacingCareerYear(entry,entryRacing as Record<string,number|string|boolean>,entryWorld!,metrics,createRng('phase4d5-entry-season-resolve'));
  verify(entryRacing.seasonActive!==true,'the next yearly racing pass must resolve the active season');
  verify(Number(entryRacing.seasons)===1,'completed racing seasons must increment the lifetime season count exactly once');
  verify(Number(entryRacing.lastSeasonAge)===17,'season results must preserve exact completion age');
  verify(Number(entryRacing.lastSeasonRaces)>=18,'completed seasons must preserve their race count');
  verify(Number(entryRacing.lastChampionshipPosition)>=1&&Number(entryRacing.lastChampionshipPosition)<=20,'championship position must be bounded');
  verify(Number(entryRacing.lastSeasonWins)>=0&&Number(entryRacing.lastSeasonPodiums)>=Number(entryRacing.lastSeasonWins),'wins and podium totals must remain internally coherent');
  verify(Number(entryRacing.lastSeasonScore)>=0&&Number(entryRacing.lastSeasonScore)<=100,'season performance must be bounded');
  verify(Number(entryRacing.lastSeasonIncidents)>=0&&Number(entryRacing.lastSeasonIncidents)<=Number(entryRacing.lastSeasonRaces),'abstract incident counts must remain bounded by season rounds');
  verify(Number(entryRacing.lastSeasonMechanicalIssues)>=0&&Number(entryRacing.lastSeasonMechanicalIssues)<=Number(entryRacing.lastSeasonRaces),'mechanical issue counts must remain bounded by season rounds');
  verify(Number(entryRacing.seasonSalaryDue)===Number(entryRacing.salary),'completed seasons must stamp the exact contracted salary before contract transitions');
  verify(Number(entryRacing.seasonPrizeDue)>0,'completed seasons must stamp bounded prize earnings for annual finance settlement');
  const financeState:any=createNewGame({seed:'phase4d5-racing-finance'});financeState.character.age=17;financeState.character.countryId='test';financeState.employment={current:undefined,partTimeJobs:[]};financeState.specialCareers.racing={lastSeasonAge:17,seasonSalaryDue:100000,seasonPrizeDue:50000};financeState.economy={salaryIndex:1,inflationIndex:1};financeState.assets={properties:[],vehicles:[],collectibles:[]};financeState.investments={positions:[],prices:{},history:{}};financeState.businesses=[];financeState.pets=[];financeState.relationships=[];financeState.npcs={};financeState.finances={cash:0,liabilities:[]};financeState.legacy={totalFamilyWealth:0};financeState.flags={};processAnnualFinance(financeState);verify(financeState.finances.annualIncome===150000,'same-age racing salary and prize accrual must enter the normal annual finance income total');verify(financeState.finances.taxesPaid>0,'racing season income must participate in normal annual taxation instead of bypassing finance');
  verify(racingSeasonHistory(entry).length===1,'new detailed racing history must begin with the first 4D5-completed season');
  verify(Number(entryRacing.contractRemaining)===Math.max(0,termBefore-1),'racing contracts must tick down exactly once per year');
  const seasonsAfter=Number(entryRacing.seasons);const historyAfter=racingSeasonHistory(entry).length;processRacingCareerYear(entry,entryRacing as Record<string,number|string|boolean>,entryWorld!,metrics,createRng('phase4d5-entry-season-resolve'));verify(Number(entryRacing.seasons)===seasonsAfter&&racingSeasonHistory(entry).length===historyAfter,'same-age racing processing must be idempotent');

  const legacy=createNewGame({seed:'phase4d5-racing-legacy'});legacy.character.age=19;legacy.currentYear=2045;legacy.character.secondary.athleticism=78;legacy.specialCareers.racing={active:true,skill:72,reputation:48,seasons:1,titles:0,years:3};const legacyWorld=ensureSpecialCareerWorld(legacy,'racing','motorsport',{announce:false});ensureSpecialCareerRelationships(legacy,legacyWorld);const legacyWorldId=legacyWorld.id;const legacyNpcIds=legacyWorld.members.map(member=>member.npcId).join('|');legacy.character.age=21;legacy.currentYear=2047;legacy.actionLedger.age=21;legacy.actionLedger.uses={};
  verify(racingSeasonHistory(legacy).length===0,'4D5 must not fabricate detailed season history for pre-4D5 racing results');
  const legacySeason=beginRacingSeason(legacy,72);verify(legacySeason.success,'an established legacy racer must conform to the new season lifecycle without rejoining');
  verify(activeSpecialCareerWorld(legacy,'racing')?.id===legacyWorldId,'legacy racing normalization must preserve the existing team world');
  verify(legacyWorld.members.map(member=>member.npcId).join('|')===legacyNpcIds,'legacy racing normalization must preserve the existing team NPC roster');
  verify(Number(legacy.specialCareers.racing.seasons)===1,'legacy normalization must preserve old aggregate season counts exactly');
  verify(legacy.specialCareers.racing.contractActive===true&&Number(legacy.specialCareers.racing.salary)>0,'legacy active racers must receive a generalized contract state without resetting history');
  legacy.character.age=22;legacy.currentYear=2048;processRacingCareerYear(legacy,legacy.specialCareers.racing as Record<string,number|string|boolean>,legacyWorld,metrics,createRng('phase4d5-legacy-resolve'));verify(Number(legacy.specialCareers.racing.seasons)===2,'the first 4D5 season must append to legacy aggregate history');verify(racingSeasonHistory(legacy).length===1,'only the new 4D5 season should receive fabricated-detail-free season history');

  const renewal=createNewGame({seed:'phase4d5-racing-renewal'});renewal.character.age=30;renewal.currentYear=2060;renewal.character.secondary.athleticism=100;renewal.character.secondary.stress=0;renewal.character.stats.health=100;renewal.health.fitness=100;renewal.fame.fame=85;renewal.specialCareers.racing={active:true,racingPathway:true,racingLifecycleInitialized:true,contractActive:true,freeAgent:false,skill:100,reputation:100,seasons:5,titles:1,contractYears:2,contractRemaining:1,salary:1500000,teamsPlayedFor:1};const renewalWorld=ensureSpecialCareerWorld(renewal,'racing','motorsport',{announce:false});ensureSpecialCareerRelationships(renewal,renewalWorld);renewal.specialCareers.racing.teamName=renewalWorld.name;for(const member of renewalWorld.members){const rel=renewal.relationships.find(item=>item.npcId===member.npcId);if(rel&&rel.type!=='enemy')rel.score=100;if(rel&&rel.type==='enemy')rel.score=95;}
  renewal.actionLedger.age=30;renewal.actionLedger.uses={};verify(beginRacingSeason(renewal,100).success,'elite renewal fixture must enter a final contract season');renewal.character.age=31;renewal.currentYear=2061;processRacingCareerYear(renewal,renewal.specialCareers.racing as Record<string,number|string|boolean>,renewalWorld,{momentum:100,chemistry:100,rivalry:5,prestige:100},createRng('phase4d5-renewal-season'));
  verify(renewal.specialCareers.racing.contractActive===false,'an expiring contract must stop being active before renewal acceptance');
  const renewalOffer=racingContractOffer(renewal);verify(Boolean(renewalOffer)&&renewalOffer?.kind==='renewal','elite final-season performance must produce a renewal offer');
  const renewalWorldCount=specialCareerWorlds(renewal,'racing').length;renewal.actionLedger.age=31;renewal.actionLedger.uses={};verify(racingContractDecision(renewal,'accept').success,'a valid racing renewal must be acceptable');verify((renewal.specialCareers.racing.contractActive as boolean|undefined)===true,'renewal acceptance must restore active contract status');verify(Number(renewal.specialCareers.racing.contractRemaining)===renewalOffer!.years&&Number(renewal.specialCareers.racing.salary)===renewalOffer!.salary,'renewal acceptance must preserve exact offered term and salary');verify(specialCareerWorlds(renewal,'racing').length===renewalWorldCount,'renewing a racing contract must not create a duplicate team world');verify(Number(renewal.specialCareers.racing.renewals)===1,'accepted renewals must be counted exactly once');

  const released=createNewGame({seed:'phase4d5-racing-release'});released.character.age=33;released.currentYear=2063;released.character.secondary.stress=70;released.specialCareers.racing={active:true,racingPathway:true,racingLifecycleInitialized:true,contractActive:true,freeAgent:false,skill:42,reputation:25,seasons:3,titles:0,contractYears:1,contractRemaining:1,salary:180000,teamChemistry:30,engineeringChemistry:30};const releasedWorld=ensureSpecialCareerWorld(released,'racing','motorsport',{announce:false});ensureSpecialCareerRelationships(released,releasedWorld);released.character.age=34;released.currentYear=2064;processRacingCareerYear(released,released.specialCareers.racing as Record<string,number|string|boolean>,releasedWorld,{momentum:35,chemistry:35,rivalry:75,prestige:40},createRng('phase4d5-release-year'));verify(Number(released.specialCareers.racing.missedSeasons)===1,'skipping a contracted racing season must be recorded instead of silently paying full performance credit');verify(released.specialCareers.racing.contractActive===false,'an expired poor contract must end cleanly');verify(released.specialCareers.racing.freeAgent===true&&released.specialCareers.racing.active===false,'a low-profile missed final season must release the racer into free agency');verify(releasedWorld.active===false,'team release must archive the former team immediately');verify(racingContractOffer(released)===undefined,'a poor missed final contract year must not manufacture a guaranteed renewal offer');

  const finalSeason=createNewGame({seed:'phase4d5-racing-final-season-pay'});finalSeason.character.age=59;finalSeason.currentYear=2089;finalSeason.character.secondary.athleticism=95;finalSeason.character.secondary.stress=10;finalSeason.character.stats.health=95;finalSeason.health.fitness=95;finalSeason.specialCareers.racing={active:true,racingPathway:true,racingLifecycleInitialized:true,contractActive:true,freeAgent:false,skill:92,reputation:80,seasons:20,titles:3,contractYears:1,contractRemaining:1,salary:2200000,teamsPlayedFor:3};const finalWorld=ensureSpecialCareerWorld(finalSeason,'racing','motorsport',{announce:false});ensureSpecialCareerRelationships(finalSeason,finalWorld);finalSeason.specialCareers.racing.teamName=finalWorld.name;finalSeason.actionLedger.age=59;finalSeason.actionLedger.uses={};verify(beginRacingSeason(finalSeason,90).success,'a contracted racer must be able to enter the final season before age-based contract retirement');finalSeason.character.age=60;finalSeason.currentYear=2090;processRacingCareerYear(finalSeason,finalSeason.specialCareers.racing as Record<string,number|string|boolean>,finalWorld,{momentum:88,chemistry:80,rivalry:25,prestige:82},createRng('phase4d5-final-season'));verify(finalSeason.specialCareers.racing.retired===true,'an expiring racing contract at the hard career boundary must resolve to retirement');verify(Number(finalSeason.specialCareers.racing.lastSeasonAge)===60&&Number(finalSeason.specialCareers.racing.seasonSalaryDue)===2200000,'final-season salary accrual must survive retirement in the same annual pass');verify(Number(finalSeason.specialCareers.racing.seasonPrizeDue)>0,'final-season prize accrual must survive retirement in the same annual pass');

  const freeAgent=createNewGame({seed:'phase4d5-racing-free-agent'});freeAgent.character.age=28;freeAgent.currentYear=2058;freeAgent.character.secondary.athleticism=96;freeAgent.specialCareers.racing={active:false,racingPathway:true,racingLifecycleInitialized:true,contractActive:false,freeAgent:true,skill:96,reputation:86,seasons:4,titles:0,bestSeasonScore:88,teamsPlayedFor:1};const oldTeam=ensureSpecialCareerWorld(freeAgent,'racing','motorsport',{announce:false});ensureSpecialCareerRelationships(freeAgent,oldTeam);const oldId=oldTeam.id;archiveSpecialCareerWorld(oldTeam,27);freeAgent.actionLedger.age=28;freeAgent.actionLedger.uses={};const seek=seekRacingContract(freeAgent);verify(seek.success,'a strong free agent must be able to generate a new team offer');const newOffer=racingContractOffer(freeAgent);verify(Boolean(newOffer)&&newOffer?.kind==='new_team','free-agent pursuit must create a new-team contract offer rather than a fake active team');verify(activeSpecialCareerWorld(freeAgent,'racing')===undefined,'seeking a contract must not create a team world before the player accepts');freeAgent.actionLedger.uses={};verify(racingContractDecision(freeAgent,'accept').success,'a free-agent team offer must be acceptable');const newWorld=activeSpecialCareerWorld(freeAgent,'racing');verify(Boolean(newWorld)&&newWorld!.id!==oldId,'accepting a new-team offer must create a genuinely new persistent team world');verify(newWorld!.name===newOffer!.team,'accepted team movement must preserve the exact offered team name');verify(specialCareerWorlds(freeAgent,'racing').some(world=>world.id===oldId&&!world.active),'the prior racing team must remain archived as career history');verify(Number(freeAgent.specialCareers.racing.teamsPlayedFor)===2,'team movement must increment teams-played-for without losing old history');

  const expiry=createNewGame({seed:'phase4d5-racing-offer-expiry'});expiry.character.age=27;expiry.specialCareers.racing={active:true,racingPathway:true,racingLifecycleInitialized:true,contractActive:false,freeAgent:false,contractOfferPending:true,contractOfferKind:'renewal',contractOfferTeam:'Apex Thread Racing',contractOfferYears:2,contractOfferSalary:800000,contractOfferExpiresAge:27};const expiryWorld=ensureSpecialCareerWorld(expiry,'racing','motorsport',{announce:false});expiry.character.age=29;verify(expireRacingContractOffer(expiry),'expired racing offers must be cleared by a global yearly expiry pass');verify(expiry.specialCareers.racing.contractOfferPending===false&&expiry.specialCareers.racing.freeAgent===true,'an expired renewal must move the racer into free agency');verify(expiryWorld.active===false,'an expired renewal must archive the former team instead of leaving it current forever');

  const retired=createNewGame({seed:'phase4d5-racing-retire'});retired.character.age=42;retired.specialCareers.racing={active:true,racingPathway:true,racingLifecycleInitialized:true,contractActive:true,freeAgent:false,skill:80,seasons:12,titles:2,contractRemaining:2,salary:900000};const retiredWorld=ensureSpecialCareerWorld(retired,'racing','motorsport',{announce:false});verify(retireRacingCareer(retired).success,'an established racer with no season underway must be able to retire explicitly');verify(retired.specialCareers.racing.retired===true&&retired.specialCareers.racing.active===false,'explicit retirement must enter a clean terminal racing state');verify(retiredWorld.active===false,'retirement must archive the current team world instead of deleting it');verify(!beginRacingSeason(retired,80).success,'retired racers must not be able to start new seasons');verify(!joinRacingPath(retired).success,'retired racers must not be able to re-enter the racing pathway');

  const history=createNewGame({seed:'phase4d5-racing-history-bound'});history.character.age=20;history.currentYear=2050;history.character.secondary.athleticism=100;history.character.secondary.stress=5;history.character.stats.health=100;history.health.fitness=100;history.specialCareers.racing={active:true,racingPathway:true,racingLifecycleInitialized:true,contractActive:true,freeAgent:false,skill:100,reputation:90,seasons:0,titles:0,contractYears:99,contractRemaining:99,salary:500000,teamsPlayedFor:1};const historyWorld=ensureSpecialCareerWorld(history,'racing','motorsport',{announce:false});ensureSpecialCareerRelationships(history,historyWorld);history.specialCareers.racing.teamName=historyWorld.name;
  for(let index=0;index<7;index+=1){history.actionLedger.age=history.character.age;history.actionLedger.uses={};verify(beginRacingSeason(history,90).success,`racing season ${index+1} must start in the bounded-history fixture`);history.character.age+=1;history.currentYear+=1;processRacingCareerYear(history,history.specialCareers.racing as Record<string,number|string|boolean>,historyWorld,{momentum:90,chemistry:85,rivalry:20,prestige:85},createRng(`phase4d5-history-${index}`));}
  verify(Number(history.specialCareers.racing.seasons)===7,'lifetime racing season totals must keep growing past the detailed history cap');verify(racingSeasonHistory(history).length===6,'detailed racing season history must remain bounded to six recent seasons');

  return checks;
}
