import { useState } from 'react';
import type { EngineResult, GameState } from '../types/game';
import { BottomSheet } from '../components/BottomSheet';
import { LicenseQuiz } from '../components/LicenseQuiz';
import { gameEngine } from '../stores/gameStore';
import { countries } from '../data/countries';
import { crimes } from '../data/crimes';

export function ActivitiesScreen({state,onResult}:{state:GameState;onResult:(r:EngineResult)=>void}){const[sheet,setSheet]=useState<string>();const[license,setLicense]=useState<'driving'|'boating'|'pilot'>('driving');const[dest,setDest]=useState(state.character.countryId);
  return <main className="screen"><div className="screen-title"><div><p className="eyebrow">Things to do</p><h1>Activities</h1></div></div>
    <section className="activity-section"><h2>Wellness</h2><div className="activity-grid">{[['gym','Gym'],['running','Run'],['walking','Walk'],['martial_arts','Martial arts'],['meditation','Meditate'],['diet','Eat intentionally']].map(([id,label])=><button key={id} onClick={()=>onResult(gameEngine.performActivity(id))}><span>＋</span>{label}</button>)}</div></section>
    <section className="activity-section"><h2>Explore</h2><div className="menu-list"><button onClick={()=>setSheet('travel')}><span><strong>Travel</strong><small>Vacations, destinations, emigration</small></span><b>›</b></button><button onClick={()=>setSheet('licenses')}><span><strong>Licenses</strong><small>Driving, boating, pilot tests</small></span><b>›</b></button><button onClick={()=>setSheet('social')}><span><strong>Social media</strong><small>Post, build followers, create fame</small></span><b>›</b></button></div></section>
    <section className="activity-section"><h2>Risk & recovery</h2><div className="menu-list"><button onClick={()=>setSheet('crime')}><span><strong>Crime</strong><small>Abstract risk, reward, arrest, sentencing</small></span><b>›</b></button><button onClick={()=>setSheet('health')}><span><strong>Healthcare</strong><small>Conditions, treatment, rehabilitation</small></span><b>›</b></button><button onClick={()=>setSheet('habits')}><span><strong>Risky habits</strong><small>Fictionalized addiction consequences</small></span><b>›</b></button></div></section>
    <section className="activity-section"><h2>Unusual ventures</h2><div className="activity-grid">{[['museum','Museum'],['zoo','Zoo'],['secretAgency','Secret agency'],['commune','Commune'],['casino','Casino resort']].map(([kind,label])=><button key={kind} onClick={()=>onResult(gameEngine.startSpecial(kind as 'museum'))}><span>◇</span>{label}</button>)}</div></section>

    <BottomSheet open={sheet==='travel'} title="Travel & emigration" onClose={()=>setSheet(undefined)}><label className="form-field"><span>Destination country</span><select value={dest} onChange={e=>setDest(e.target.value)}>{countries.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="action-grid"><button onClick={()=>onResult(gameEngine.travel(dest))}>Take vacation</button><button onClick={()=>onResult(gameEngine.travel(dest,undefined,true))}>Family trip</button><button onClick={()=>onResult(gameEngine.emigrate(dest))}>Emigrate</button></div><p className="muted">Country economics are deliberately simplified game-balance profiles, not real-world statistical claims.</p></BottomSheet>
    <BottomSheet open={sheet==='licenses'} title="License tests" onClose={()=>setSheet(undefined)}><div className="segmented">{(['driving','boating','pilot'] as const).map(k=><button className={license===k?'active':''} key={k} onClick={()=>setLicense(k)}>{k}</button>)}</div><LicenseQuiz key={license} kind={license} onResult={onResult}/><p className="muted">Touch and keyboard friendly. These are fictional safety-oriented skill checks, not real licensing exams.</p></BottomSheet>
    <BottomSheet open={sheet==='social'} title="Social media" onClose={()=>setSheet(undefined)}><div className="sheet-stat-grid"><div><small>Followers</small><strong>{state.fame.followers.toLocaleString()}</strong></div><div><small>Engagement</small><strong>{Math.round(state.fame.engagement)}%</strong></div><div><small>Fame</small><strong>{Math.round(state.fame.fame)}</strong></div><div><small>Reputation</small><strong>{Math.round(state.fame.publicReputation)}</strong></div></div><div className="action-grid">{([['loop','Loopline'],['video','Longform'],['photo','PrismPic'],['micro','Chattermark'],['live','BeaconLive']] as const).map(([id,label])=><button key={id} onClick={()=>onResult(gameEngine.post(id))}>Post on {label}</button>)}</div>{state.fame.fame>=12&&<div className="sheet-section"><h3>Publicity</h3><div className="action-grid">{(['interview','commercial','book','event','endorsement','respond_fans'] as const).map(a=><button key={a} onClick={()=>onResult(gameEngine.fameAction(a))}>{a.replace('_',' ')}</button>)}</div></div>}</BottomSheet>
    <BottomSheet open={sheet==='crime'} title="Crime & legal risk" onClose={()=>setSheet(undefined)}><p className="muted">Crime is simulated as abstract probability, money, injury, notoriety, evidence, and sentencing. No operational instructions are modeled.</p>{state.flags.pendingCharge&&<div className="warning-card"><strong>Pending case</strong><p>Authorities have connected you to an incident.</p><div className="action-grid"><button onClick={()=>onResult(gameEngine.resolveCase('public','contest'))}>Public lawyer · contest</button><button onClick={()=>onResult(gameEngine.resolveCase('experienced','contest'))}>Experienced lawyer</button><button onClick={()=>onResult(gameEngine.resolveCase('budget','plead'))}>Plea route</button></div></div>}{state.legal.imprisoned?<><div className="warning-card"><strong>{state.legal.prisonSecurity} security</strong><p>{state.legal.sentenceRemaining} years remaining.</p></div><div className="action-grid">{(['exercise','work','befriend','behave','trouble','appeal'] as const).map(a=><button key={a} onClick={()=>onResult(gameEngine.prisonAction(a))}>{a}</button>)}<button onClick={()=>onResult(gameEngine.escape(55))}>Attempt procedural escape</button></div></>:<div className="list-compact">{crimes.filter(c=>c.minAge<=state.character.age).slice(0,30).map(c=><button key={c.id} onClick={()=>onResult(gameEngine.commitCrime(c.id))}><span><strong>{c.name}</strong><small>Detection {Math.round(c.detectionChance*100)}% · abstract reward up to {c.rewardRange[1].toLocaleString()}</small></span><b>›</b></button>)}</div>}</BottomSheet>
    <BottomSheet open={sheet==='health'} title="Healthcare" onClose={()=>setSheet(undefined)}>{state.health.conditions.length?<div className="stack">{state.health.conditions.map(c=><div className="condition-card" key={c.id}><strong>{c.name}</strong><small>Severity {Math.round(c.severity)} · {c.chronic?'chronic':'temporary'}</small><div className="action-grid"><button onClick={()=>onResult(gameEngine.treat(c.id,'general'))}>Doctor</button><button onClick={()=>onResult(gameEngine.treat(c.id,'specialist'))}>Specialist</button></div></div>)}</div>:<p className="empty-card">No active conditions.</p>}<p className="muted">Health outcomes are game mechanics and are not medical advice.</p></BottomSheet>
    <BottomSheet open={sheet==='habits'} title="Risky habits & recovery" onClose={()=>setSheet(undefined)}><div className="action-grid">{(['alcohol','gambling','smoking','fictional_substance'] as const).map(k=><button key={k} onClick={()=>onResult(gameEngine.riskyHabit(k))}>{k.replace('_',' ')}</button>)}</div>{state.health.addictions.map(a=><div className="condition-card" key={a.kind}><strong>{a.kind}</strong><small>Severity {Math.round(a.severity)} · {a.recovering?'recovering':'active'}</small>{!a.recovering&&<button onClick={()=>onResult(gameEngine.rehab(a.kind))}>Enter rehabilitation</button>}</div>)}</BottomSheet>
  </main>;
}
