import { useMemo, useState } from 'react';
import type { EngineResult, GameState } from '../types/game';
import { SearchField } from '../components/SearchField';
import { EstatePlanningPanel } from '../components/EstatePlanningPanel';
import { AssetPurchaseSheet, type AssetPurchaseTarget } from '../components/AssetPurchaseSheet';
import { AssetSaleSheet, type AssetSaleTarget } from '../components/AssetSaleSheet';
import { gameEngine } from '../stores/gameStore';
import { assetValue, getSecuredLoanStatus, liabilityValue, netWorth } from '../systems/FinanceSystem';
import { propertyDefinitions, vehicleDefinitions, luxuryVehicleDefinitions, securities, businessIndustries, petVariants, collectibleDefinitions } from '../data/assets';
import { exactMoney, formatMoney } from '../core/format';
import { actionAllowed } from '../core/actionEconomy';

export function AssetsScreen({state,onResult}:{state:GameState;onResult:(r:EngineResult)=>void}){
  const[tab,setTab]=useState<'money'|'property'|'invest'|'business'|'estate'|'more'>('money');
  const[propertyView,setPropertyView]=useState<'browse'|'owned'>('browse');
  const[q,setQ]=useState('');
  const[amount,setAmount]=useState(1000);
  const[bizIndustry,setBizIndustry]=useState('software');
  const[bizName,setBizName]=useState('');
  const[purchaseTarget,setPurchaseTarget]=useState<AssetPurchaseTarget>();
  const[saleTarget,setSaleTarget]=useState<AssetSaleTarget>();
  const portfolio=state.investments.positions.reduce((s,p)=>s+p.units*(state.investments.prices[p.securityId]??0),0);
  const search=q.trim().toLowerCase();
  const props=useMemo(()=>propertyDefinitions.filter(p=>!search||p.name.toLowerCase().includes(search)).slice(0,45),[search]);
  const vehicles=useMemo(()=>[...vehicleDefinitions,...luxuryVehicleDefinitions].filter(v=>!search||v.name.toLowerCase().includes(search)),[search]);

  return <main className="screen">
    <div className="screen-title"><div><p className="eyebrow">Money & things</p><h1>Assets</h1></div><strong className="net-worth" title={exactMoney(netWorth(state))}>{formatMoney(netWorth(state))}</strong></div>
    <div className="segmented segmented--scroll"><button className={tab==='money'?'active':''} onClick={()=>setTab('money')}>Money</button><button className={tab==='property'?'active':''} onClick={()=>setTab('property')}>Property</button><button className={tab==='invest'?'active':''} onClick={()=>setTab('invest')}>Invest</button><button className={tab==='business'?'active':''} onClick={()=>setTab('business')}>Business</button><button className={tab==='estate'?'active':''} onClick={()=>setTab('estate')}>Estate</button><button className={tab==='more'?'active':''} onClick={()=>setTab('more')}>More</button></div>

    {tab==='money'&&<MoneyView state={state} portfolio={portfolio}/>}
    {tab==='property'&&<PropertyView state={state} view={propertyView} setView={setPropertyView} q={q} setQ={setQ} props={props} vehicles={vehicles} onResult={onResult} onPurchase={setPurchaseTarget} onSell={setSaleTarget}/>}
    {tab==='invest'&&(state.character.age<18?<section className="hero-card"><p className="eyebrow">Locked</p><h2>Investing unlocks at 18</h2><p>Your childhood finances are managed as dependent finances. Market trading becomes available when you reach adulthood.</p></section>:<><section className="hero-card"><p className="eyebrow">Market regime</p><h2>{state.investments.marketRegime}</h2><p>All securities are fictional. Prices are generated from your save seed and evolve only inside the game.</p></section><label className="form-field"><span>Trade amount</span><input type="number" min="10" step="100" value={amount} onChange={e=>setAmount(Number(e.target.value)||0)}/></label><div className="stack">{securities.map(s=>{const price=state.investments.prices[s.id]??s.basePrice;const pos=state.investments.positions.find(p=>p.securityId===s.id);return <div className="market-card" key={s.id}><div><strong>{s.ticker} · {s.name}</strong><small>{s.type} · {price.toFixed(2)}{pos?` · you own ${formatMoney(pos.units*price)}`:''}</small></div><div className="button-row"><button onClick={()=>onResult(gameEngine.invest(s.id,amount))}>Buy</button>{pos&&<button onClick={()=>onResult(gameEngine.sellInvestment(s.id))}>Sell all</button>}</div></div>})}</div></>)}
    {tab==='business'&&<><section className="action-card"><h2>Start company</h2><label className="form-field"><span>Name</span><input value={bizName} onChange={e=>setBizName(e.target.value)} placeholder="Company name"/></label><label className="form-field"><span>Industry</span><select value={bizIndustry} onChange={e=>setBizIndustry(e.target.value)}>{businessIndustries.map(i=><option key={i.id} value={i.id}>{i.name} · {i.startupCapital.toLocaleString()}</option>)}</select></label><button className="full-button" disabled={state.character.age<18||!actionAllowed(state,{policy:'business.start'})} onClick={()=>onResult(gameEngine.startBusiness(bizIndustry,bizName))}>Found company</button></section>{state.businesses.map(b=><section className="business-card" key={b.id}><div className="section-heading"><div><p className="eyebrow">{b.bankrupt?'Closed':'Operating'}</p><h2>{b.name}</h2></div><strong title={exactMoney(b.valuation)}>{formatMoney(b.valuation)}</strong></div><div className="finance-grid"><div title={exactMoney(b.revenue)}><small>Revenue</small><strong>{formatMoney(b.revenue)}</strong></div><div title={exactMoney(b.profit)}><small>Profit</small><strong>{formatMoney(b.profit)}</strong></div><div><small>Employees</small><strong>{b.employees}</strong></div><div><small>Reputation</small><strong>{Math.round(b.reputation)}</strong></div></div>{!b.bankrupt&&<div className="action-grid"><button disabled={!actionAllowed(state,{policy:'business.product',target:b.id})} onClick={()=>onResult(gameEngine.addBusinessProduct(b.id))}>Launch product</button><button onClick={()=>onResult(gameEngine.tuneBusiness(b.id,'marketingBudget',Math.max(1000,b.marketingBudget*1.25)))}>Raise marketing</button><button onClick={()=>onResult(gameEngine.tuneBusiness(b.id,'compensationIndex',Math.min(1.8,b.compensationIndex+.1)))}>Raise pay</button></div>}</section>)}</>}
    {tab==='estate'&&<EstatePlanningPanel state={state} onResult={onResult}/>}
    {tab==='more'&&<MoreAssets state={state} onResult={onResult}/>}
    {purchaseTarget&&<AssetPurchaseSheet state={state} target={purchaseTarget} onResult={onResult} onClose={()=>setPurchaseTarget(undefined)}/>}
    {saleTarget&&<AssetSaleSheet state={state} target={saleTarget} onResult={onResult} onClose={()=>setSaleTarget(undefined)}/>}
  </main>;
}

function MoneyView({state,portfolio}:{state:GameState;portfolio:number}){
  const creditDebt=state.finances.credit.accounts.filter(account=>account.status==='open'&&account.balance>0);
  return <><div className="finance-grid"><div title={exactMoney(state.finances.cash)}><small>Cash</small><strong>{formatMoney(state.finances.cash)}</strong></div><div title={exactMoney(assetValue(state))}><small>Assets</small><strong>{formatMoney(assetValue(state))}</strong></div><div title={exactMoney(liabilityValue(state))}><small>Debt</small><strong>{formatMoney(liabilityValue(state))}</strong></div><div title={exactMoney(portfolio)}><small>Portfolio</small><strong>{formatMoney(portfolio)}</strong></div></div>{state.finances.lastYearSummary&&<section className="action-card"><p className="eyebrow">Last year</p><h2>Financial summary</h2>{Object.entries(state.finances.lastYearSummary).map(([k,v])=><p className="history-line" key={k}><span>{k.replace(/([A-Z])/g,' $1')}</span><strong title={exactMoney(v)}>{formatMoney(v)}</strong></p>)}</section>}<section className="action-card"><h2>Liabilities</h2>{state.finances.liabilities.length||creditDebt.length?<>{state.finances.liabilities.map(l=>{const secured=getSecuredLoanStatus(state,l);return <div className={`liability-card${secured?.status==='delinquent'?' liability-card--danger':''}`} key={l.id}><div className="liability-card__main"><span>{l.kind} · {Math.round(l.annualRate*1000)/10}%<small>{formatMoney(l.annualPayment)}/yr · {l.remainingYears} yr remaining{secured?` · ${secured.collateralName}`:''}</small>{secured?.status==='delinquent'&&<em>{formatMoney(secured.arrears)} past due · {secured.consequence} risk</em>}</span><strong title={exactMoney(l.balance)}>{formatMoney(l.balance)}</strong></div></div>})}{creditDebt.map(account=><p className="history-line" key={account.id}><span>credit card · {Math.round(account.annualRate*1000)/10}%<small>{account.productName}{(account.pastDueAmount??0)>0?` · ${formatMoney(account.pastDueAmount??0)} past due`:''}</small></span><strong title={exactMoney(account.balance)}>{formatMoney(account.balance)}</strong></p>)}<p className="muted asset-payment-note">Required payments and auto-pay preferences are managed from Credit & Banking → Bills & Payments.</p></>:<p className="muted">No debt.</p>}</section></>;
}

function PropertyView({state,view,setView,q,setQ,props,vehicles,onResult,onPurchase,onSell}:{state:GameState;view:'browse'|'owned';setView:(view:'browse'|'owned')=>void;q:string;setQ:(value:string)=>void;props:typeof propertyDefinitions;vehicles:Array<(typeof vehicleDefinitions)[number]|(typeof luxuryVehicleDefinitions)[number]>;onResult:(r:EngineResult)=>void;onPurchase:(target:AssetPurchaseTarget)=>void;onSell:(target:AssetSaleTarget)=>void}){
  return <>
    <div className="segmented asset-ownership-toggle"><button className={view==='browse'?'active':''} onClick={()=>setView('browse')}>Browse</button><button className={view==='owned'?'active':''} onClick={()=>setView('owned')}>Owned</button></div>
    {view==='browse'?<><SearchField value={q} onChange={setQ} placeholder="Search homes or vehicles"/><section className="asset-market-section"><div className="section-heading"><div><p className="eyebrow">Property market</p><h2>Homes</h2></div></div><div className="list-compact">{props.map(p=><button key={p.id} disabled={state.character.age<18} onClick={()=>onPurchase({kind:'home',typeId:p.id,name:p.name,price:Math.round(p.basePrice*state.economy.housingIndex)})}><span><strong>{p.name}</strong><small>{Math.round(p.basePrice*state.economy.housingIndex).toLocaleString()} · amenities: {p.amenities.join(', ')}</small></span><b>Options</b></button>)}</div></section><section className="asset-market-section"><div className="section-heading"><div><p className="eyebrow">Vehicle market</p><h2>Cars & vehicles</h2></div></div><div className="list-compact">{vehicles.map(v=><button key={v.id} disabled={state.character.age<16} onClick={()=>onPurchase({kind:'vehicle',typeId:v.id,name:v.name,price:v.price,financeEligible:v.category==='car'||v.category==='motorcycle'})}><span><strong>{v.name}</strong><small>{v.category} · {v.price.toLocaleString()}</small></span><b>Options</b></button>)}</div></section></>:<OwnedAssets state={state} onResult={onResult} onSell={onSell}/>}
  </>;
}

function OwnedAssets({state,onResult,onSell}:{state:GameState;onResult:(r:EngineResult)=>void;onSell:(target:AssetSaleTarget)=>void}){
  return <div className="owned-assets-stack"><section className="action-card"><div className="section-heading"><div><p className="eyebrow">Real estate</p><h2>Your homes</h2></div><strong>{state.assets.properties.length}</strong></div>{state.assets.properties.map(p=>{const loan=state.finances.liabilities.find(l=>l.kind==='mortgage'&&(l.assetId===p.id||l.id===p.mortgageId));const secured=loan?getSecuredLoanStatus(state,loan):undefined;return <div className={`owned-card${secured?.status==='delinquent'?' owned-card--at-risk':''}`} key={p.id}><div><strong>{p.name}</strong><small>{p.location} · value {formatMoney(p.marketValue)} · condition {Math.round(p.condition)}{loan?` · ${formatMoney(loan.balance)} financed · auto-pay ${loan.autoPay===false?'off':'on'}`:' · owned outright'}</small>{secured?.status==='delinquent'&&<em className="asset-risk-label">{formatMoney(secured.arrears)} past due · foreclosure risk</em>}</div><div className="action-grid"><button disabled={!actionAllowed(state,{policy:'property.renovate',target:p.id})} onClick={()=>onResult(gameEngine.renovateProperty(p.id))}>Renovate</button>{!p.rental&&<button onClick={()=>onResult(gameEngine.rentProperty(p.id))}>Rent out</button>}<button onClick={()=>onSell({kind:'property',id:p.id})}>Sell</button></div></div>})}{!state.assets.properties.length&&<p className="muted">No homes or real estate yet.</p>}</section><section className="action-card"><div className="section-heading"><div><p className="eyebrow">Garage</p><h2>Your vehicles</h2></div><strong>{state.assets.vehicles.length}</strong></div>{state.assets.vehicles.map(v=>{const loan=state.finances.liabilities.find(l=>l.kind==='car'&&l.assetId===v.id);const secured=loan?getSecuredLoanStatus(state,loan):undefined;return <div className={`owned-card${secured?.status==='delinquent'?' owned-card--at-risk':''}`} key={v.id}><div><strong>{v.name}</strong><small>Value {formatMoney(v.value)} · condition {Math.round(v.condition)} · {v.mileage.toLocaleString()} km{loan?` · ${formatMoney(loan.balance)} financed · auto-pay ${loan.autoPay===false?'off':'on'}`:' · owned outright'}</small>{secured?.status==='delinquent'&&<em className="asset-risk-label">{formatMoney(secured.arrears)} past due · repossession risk</em>}</div><div className="button-row"><button onClick={()=>onResult(gameEngine.repairVehicle(v.id))}>Repair</button><button onClick={()=>onSell({kind:'vehicle',id:v.id})}>Sell</button></div></div>})}{!state.assets.vehicles.length&&<p className="muted">No vehicles yet.</p>}</section><p className="muted asset-payment-note">Financing status is shown here for context. Manage required payments and auto-pay in Credit & Banking.</p></div>;
}

function MoreAssets({state,onResult}:{state:GameState;onResult:(r:EngineResult)=>void}){
  const[section,setSection]=useState<'pets'|'collectibles'>('pets');
  return <><div className="segmented"><button className={section==='pets'?'active':''} onClick={()=>setSection('pets')}>Pets</button><button className={section==='collectibles'?'active':''} onClick={()=>setSection('collectibles')}>Collectibles</button></div>{section==='pets'?<><section className="action-card"><h2>Your pets</h2>{state.pets.filter(p=>p.alive).map(p=><div className="owned-card" key={p.id}><div><strong>{p.name}</strong><small>{p.breed} · age {p.age} · health {Math.round(p.health)}</small></div><button disabled={!actionAllowed(state,[{policy:'pet.total',target:p.id},{policy:'pet.action',target:`${p.id}:spend_time`}])} onClick={()=>onResult(gameEngine.petAction(p.id,'spend_time'))}>Spend time</button></div>)}</section><div className="list-compact">{petVariants.slice(0,55).map(p=><button key={p.id} disabled={state.character.age<5||!actionAllowed(state,{policy:'pet.adopt'})} onClick={()=>onResult(gameEngine.adoptPet(p.id))}><span><strong>{p.breed}</strong><small>{p.species} · {p.price.toLocaleString()} · {p.legalTier}</small></span><b>Adopt</b></button>)}</div></>:<><section className="action-card"><h2>Collection</h2>{state.assets.collectibles.map(c=><p className="history-line" key={c.id}><span>{c.name} · {c.rarity}</span><strong title={exactMoney(c.estimatedValue)}>{formatMoney(c.estimatedValue)}</strong></p>)}</section><div className="list-compact">{collectibleDefinitions.map(c=><button key={c.id} disabled={state.character.age<12||!actionAllowed(state,[{policy:'collectible.purchase.total'},{policy:'collectible.purchase.item',target:c.id}])} onClick={()=>onResult(gameEngine.purchaseCollectible(c.id))}><span><strong>{c.name}</strong><small>{c.family} · estimated base {c.baseValue.toLocaleString()} · {c.rarity}</small></span><b>Find</b></button>)}</div></>}</>;
}
