import { useMemo, useState } from 'react';
import type { EngineResult, GameState } from '../types/game';
import { SearchField } from '../components/SearchField';
import { gameEngine } from '../stores/gameStore';
import { assetValue, liabilityValue, netWorth } from '../systems/FinanceSystem';
import { propertyDefinitions, vehicleDefinitions, luxuryVehicleDefinitions, securities, businessIndustries, petVariants, collectibleDefinitions } from '../data/assets';
import { exactMoney, formatMoney } from '../core/format';

export function AssetsScreen({state,onResult}:{state:GameState;onResult:(r:EngineResult)=>void}){const[tab,setTab]=useState<'money'|'property'|'invest'|'business'|'more'>('money');const[q,setQ]=useState('');const[amount,setAmount]=useState(1000);const[bizIndustry,setBizIndustry]=useState('software');const[bizName,setBizName]=useState('');
 const portfolio=state.investments.positions.reduce((s,p)=>s+p.units*(state.investments.prices[p.securityId]??0),0);const props=useMemo(()=>propertyDefinitions.filter(p=>p.name.toLowerCase().includes(q.toLowerCase())).slice(0,45),[q]);
 return <main className="screen"><div className="screen-title"><div><p className="eyebrow">Money & things</p><h1>Assets</h1></div><strong className="net-worth" title={exactMoney(netWorth(state))}>{formatMoney(netWorth(state))}</strong></div><div className="segmented segmented--scroll"><button className={tab==='money'?'active':''} onClick={()=>setTab('money')}>Money</button><button className={tab==='property'?'active':''} onClick={()=>setTab('property')}>Property</button><button className={tab==='invest'?'active':''} onClick={()=>setTab('invest')}>Invest</button><button className={tab==='business'?'active':''} onClick={()=>setTab('business')}>Business</button><button className={tab==='more'?'active':''} onClick={()=>setTab('more')}>More</button></div>
 {tab==='money'&&<><div className="finance-grid"><div title={exactMoney(state.finances.cash)}><small>Cash</small><strong>{formatMoney(state.finances.cash)}</strong></div><div title={exactMoney(assetValue(state))}><small>Assets</small><strong>{formatMoney(assetValue(state))}</strong></div><div title={exactMoney(liabilityValue(state))}><small>Debt</small><strong>{formatMoney(liabilityValue(state))}</strong></div><div title={exactMoney(portfolio)}><small>Portfolio</small><strong>{formatMoney(portfolio)}</strong></div></div>{state.finances.lastYearSummary&&<section className="action-card"><p className="eyebrow">Last year</p><h2>Financial summary</h2>{Object.entries(state.finances.lastYearSummary).map(([k,v])=><p className="history-line" key={k}><span>{k.replace(/([A-Z])/g,' $1')}</span><strong title={exactMoney(v)}>{formatMoney(v)}</strong></p>)}</section>}<section className="action-card"><h2>Liabilities</h2>{state.finances.liabilities.length?state.finances.liabilities.map(l=><p className="history-line" key={l.id}><span>{l.kind} · {Math.round(l.annualRate*1000)/10}%</span><strong title={exactMoney(l.balance)}>{formatMoney(l.balance)}</strong></p>):<p className="muted">No debt.</p>}</section></>}
 {tab==='property'&&<><section className="action-card"><h2>Your property</h2>{state.assets.properties.map(p=><div className="owned-card" key={p.id}><div><strong>{p.name}</strong><small>{p.location} · value {formatMoney(p.marketValue)} · condition {Math.round(p.condition)}</small></div><div className="action-grid"><button onClick={()=>onResult(gameEngine.renovateProperty(p.id))}>Renovate</button>{!p.rental&&<button onClick={()=>onResult(gameEngine.rentProperty(p.id))}>Rent out</button>}<button onClick={()=>onResult(gameEngine.sellProperty(p.id))}>Sell</button></div></div>)}{!state.assets.properties.length&&<p className="muted">No property yet.</p>}</section><SearchField value={q} onChange={setQ} placeholder="Search property market"/><div className="list-compact">{props.map(p=><button key={p.id} onClick={()=>onResult(gameEngine.purchaseProperty(p.id,true))}><span><strong>{p.name}</strong><small>{Math.round(p.basePrice*state.economy.housingIndex).toLocaleString()} · amenities: {p.amenities.join(', ')}</small></span><b>Buy</b></button>)}</div></>}
 {tab==='invest'&&<><section className="hero-card"><p className="eyebrow">Market regime</p><h2>{state.investments.marketRegime}</h2><p>All securities are fictional. Prices are generated from your save seed and evolve only inside the game.</p></section><label className="form-field"><span>Trade amount</span><input type="number" min="10" step="100" value={amount} onChange={e=>setAmount(Number(e.target.value)||0)}/></label><div className="stack">{securities.map(s=>{const price=state.investments.prices[s.id]??s.basePrice;const pos=state.investments.positions.find(p=>p.securityId===s.id);return <div className="market-card" key={s.id}><div><strong>{s.ticker} · {s.name}</strong><small>{s.type} · {price.toFixed(2)}{pos?` · you own ${formatMoney(pos.units*price)}`:''}</small></div><div className="button-row"><button onClick={()=>onResult(gameEngine.invest(s.id,amount))}>Buy</button>{pos&&<button onClick={()=>onResult(gameEngine.sellInvestment(s.id))}>Sell all</button>}</div></div>})}</div></>}
 {tab==='business'&&<><section className="action-card"><h2>Start company</h2><label className="form-field"><span>Name</span><input value={bizName} onChange={e=>setBizName(e.target.value)} placeholder="Company name"/></label><label className="form-field"><span>Industry</span><select value={bizIndustry} onChange={e=>setBizIndustry(e.target.value)}>{businessIndustries.map(i=><option key={i.id} value={i.id}>{i.name} · {i.startupCapital.toLocaleString()}</option>)}</select></label><button className="full-button" onClick={()=>onResult(gameEngine.startBusiness(bizIndustry,bizName))}>Found company</button></section>{state.businesses.map(b=><section className="business-card" key={b.id}><div className="section-heading"><div><p className="eyebrow">{b.bankrupt?'Closed':'Operating'}</p><h2>{b.name}</h2></div><strong title={exactMoney(b.valuation)}>{formatMoney(b.valuation)}</strong></div><div className="finance-grid"><div title={exactMoney(b.revenue)}><small>Revenue</small><strong>{formatMoney(b.revenue)}</strong></div><div title={exactMoney(b.profit)}><small>Profit</small><strong>{formatMoney(b.profit)}</strong></div><div><small>Employees</small><strong>{b.employees}</strong></div><div><small>Reputation</small><strong>{Math.round(b.reputation)}</strong></div></div>{!b.bankrupt&&<div className="action-grid"><button onClick={()=>onResult(gameEngine.addBusinessProduct(b.id))}>Launch product</button><button onClick={()=>onResult(gameEngine.tuneBusiness(b.id,'marketingBudget',Math.max(1000,b.marketingBudget*1.25)))}>Raise marketing</button><button onClick={()=>onResult(gameEngine.tuneBusiness(b.id,'compensationIndex',Math.min(1.8,b.compensationIndex+.1)))}>Raise pay</button></div>}</section>)}</>}
 {tab==='more'&&<MoreAssets state={state} onResult={onResult}/>}</main>;
}

function MoreAssets({state,onResult}:{state:GameState;onResult:(r:EngineResult)=>void}){const[section,setSection]=useState<'vehicles'|'pets'|'collectibles'>('vehicles');return <><div className="segmented"><button className={section==='vehicles'?'active':''} onClick={()=>setSection('vehicles')}>Vehicles</button><button className={section==='pets'?'active':''} onClick={()=>setSection('pets')}>Pets</button><button className={section==='collectibles'?'active':''} onClick={()=>setSection('collectibles')}>Collectibles</button></div>{section==='vehicles'&&<><section className="action-card"><h2>Your vehicles</h2>{state.assets.vehicles.map(v=><div className="owned-card" key={v.id}><div><strong>{v.name}</strong><small>Value {formatMoney(v.value)} · condition {Math.round(v.condition)} · {v.mileage.toLocaleString()} km</small></div><button onClick={()=>onResult(gameEngine.repairVehicle(v.id))}>Repair</button></div>)}</section><div className="list-compact">{[...vehicleDefinitions,...luxuryVehicleDefinitions].map(v=><button key={v.id} onClick={()=>onResult(gameEngine.purchaseVehicle(v.id))}><span><strong>{v.name}</strong><small>{v.category} · {v.price.toLocaleString()}</small></span><b>Buy</b></button>)}</div></>}{section==='pets'&&<><section className="action-card"><h2>Your pets</h2>{state.pets.filter(p=>p.alive).map(p=><div className="owned-card" key={p.id}><div><strong>{p.name}</strong><small>{p.breed} · age {p.age} · health {Math.round(p.health)}</small></div><button onClick={()=>onResult(gameEngine.petAction(p.id,'spend_time'))}>Spend time</button></div>)}</section><div className="list-compact">{petVariants.slice(0,55).map(p=><button key={p.id} onClick={()=>onResult(gameEngine.adoptPet(p.id))}><span><strong>{p.breed}</strong><small>{p.species} · {p.price.toLocaleString()} · {p.legalTier}</small></span><b>Adopt</b></button>)}</div></>}{section==='collectibles'&&<><section className="action-card"><h2>Collection</h2>{state.assets.collectibles.map(c=><p className="history-line" key={c.id}><span>{c.name} · {c.rarity}</span><strong title={exactMoney(c.estimatedValue)}>{formatMoney(c.estimatedValue)}</strong></p>)}</section><div className="list-compact">{collectibleDefinitions.map(c=><button key={c.id} onClick={()=>onResult(gameEngine.purchaseCollectible(c.id))}><span><strong>{c.name}</strong><small>{c.family} · estimated base {c.baseValue.toLocaleString()} · {c.rarity}</small></span><b>Find</b></button>)}</div></>}</>}
