import { useMemo, useState } from 'react';
import type { EngineResult, GameState } from '../types/game';
import { SearchField } from '../components/SearchField';
import { gameEngine } from '../stores/gameStore';
import { availableJobs } from '../systems/CareerSystem';
import { availablePrograms } from '../systems/EducationSystem';

export function CareerScreen({state,onResult}:{state:GameState;onResult:(r:EngineResult)=>void}){const[tab,setTab]=useState<'work'|'education'|'special'>('work');const[q,setQ]=useState('');const jobs=useMemo(()=>availableJobs(state).filter(j=>`${j.title} ${j.industry}`.toLowerCase().includes(q.toLowerCase())).slice(0,80),[state,q]);const programs=useMemo(()=>availablePrograms(state).filter(p=>p.name.toLowerCase().includes(q.toLowerCase())),[state,q]);const currentStudy=[...state.education].reverse().find(e=>!e.graduated&&!e.droppedOut&&!e.endAge);
 return <main className="screen"><div className="screen-title"><div><p className="eyebrow">Work & learning</p><h1>Career</h1></div></div><div className="segmented segmented--sticky"><button className={tab==='work'?'active':''} onClick={()=>setTab('work')}>Work</button><button className={tab==='education'?'active':''} onClick={()=>setTab('education')}>Education</button><button className={tab==='special'?'active':''} onClick={()=>setTab('special')}>Life paths</button></div>
 {tab==='work'&&<><section className="hero-card">{state.employment.current?<><p className="eyebrow">Current role</p><h2>{state.employment.current.title}</h2><p>{state.employment.current.company} · {state.employment.current.salary.toLocaleString()}/year</p><div className="sheet-stat-grid"><div><small>Performance</small><strong>{Math.round(state.employment.current.performance)}</strong></div><div><small>Level</small><strong>{state.employment.current.level}</strong></div><div><small>Stress</small><strong>{Math.round(state.character.secondary.stress)}</strong></div></div><div className="button-row"><button onClick={()=>onResult(gameEngine.workHarder())}>Work harder</button><button onClick={()=>onResult(gameEngine.askForRaise())}>Ask raise</button><button className="danger-soft" onClick={()=>onResult(gameEngine.resign())}>Resign</button></div></>:<><p className="eyebrow">Current role</p><h2>{state.character.age<16?'Not old enough to work yet':'Unemployed'}</h2><p>Qualified listings update from your age, education, stats, and legal history.</p></>}</section>{state.character.age>=50&&<button className="full-button" onClick={()=>onResult(gameEngine.retire())}>Retire from working life</button>}<div className="section-heading"><h2>Job market</h2><span>{jobs.length} shown</span></div><SearchField value={q} onChange={setQ} placeholder="Search qualified jobs"/><div className="list-compact">{jobs.map(job=><button key={job.id} onClick={()=>onResult(gameEngine.applyForJob(job.id))}><span><strong>{job.title}</strong><small>{job.industry} · {job.salaryRange[0].toLocaleString()}–{job.salaryRange[1].toLocaleString()}</small></span><b>Apply</b></button>)}</div><section className="action-card"><h2>Freelance</h2><div className="action-grid">{['writing','programming','design'].map(k=><button key={k} onClick={()=>onResult(gameEngine.performActivity(`freelance_${k}`))}>{k}</button>)}</div></section></>}
 {tab==='education'&&<>{currentStudy&&<section className="hero-card"><p className="eyebrow">Currently enrolled</p><h2>{currentStudy.major??currentStudy.stage}</h2><p>{currentStudy.institution}</p><div className="button-row"><button onClick={()=>onResult(gameEngine.performActivity('study'))}>Study harder</button><button onClick={()=>onResult(gameEngine.performActivity('skip_class'))}>Skip class</button><button className="danger-soft" onClick={()=>onResult(gameEngine.dropOut())}>Drop out</button></div></section>}<SearchField value={q} onChange={setQ} placeholder="Search education"/><div className="list-compact">{programs.map(p=><button key={p.id} onClick={()=>onResult(gameEngine.enroll(p.id))}><span><strong>{p.name}</strong><small>{p.years} years · base tuition {p.tuition.toLocaleString()} · intelligence {p.minIntelligence}+</small></span><b>Apply</b></button>)}</div><section className="action-card"><h2>Education history</h2>{state.education.map((e,i)=><p className="history-line" key={`${e.stage}-${i}`}><strong>{e.stage.replace('_',' ')}</strong><span>{e.graduated?'Graduated':e.droppedOut?'Dropped out':'In progress'}</span></p>)}</section></>}
 {tab==='special'&&<SpecialPaths state={state} onResult={onResult}/>}</main>;
}

function SpecialPaths({state,onResult}:{state:GameState;onResult:(r:EngineResult)=>void}){return <div className="special-paths">
 <Path title="Acting" stat={`Skill ${Math.round(Number(state.specialCareers.acting?.skill??0))}`} actions={[['Lesson',()=>gameEngine.actingLesson()],['Find agent',()=>gameEngine.actingAgent()],['Audition',()=>gameEngine.actingAudition()]]} onResult={onResult}/>
 <Path title="Music" stat={`Skill ${Math.round(Number(state.specialCareers.music?.skill??0))}`} actions={[['Practice vocals',()=>gameEngine.musicPractice('vocals')],['Release song',()=>gameEngine.musicRelease('song')],['Release album',()=>gameEngine.musicRelease('album')],['Tour',()=>gameEngine.musicTour()]]} onResult={onResult}/>
 <Path title="Professional sports" stat={String(state.specialCareers.sports?.sport??'Choose a sport')} actions={[['Join basketball',()=>gameEngine.sportsJoin('Basketball')],['Train',()=>gameEngine.sportsTrain()],['Seek pro contract',()=>gameEngine.sportsPro()]]} onResult={onResult}/>
 <Path title="Combat sports" stat={`Wins ${Number(state.specialCareers.combat?.wins??0)} · titles ${Number(state.specialCareers.combat?.titles??0)}`} actions={[['Train',()=>gameEngine.combatTrain()],['Take fight',()=>gameEngine.combatFight()]]} onResult={onResult}/>
 <Path title="Politics" stat={`Office level ${Number(state.specialCareers.politics?.office??0)} · approval ${Math.round(Number(state.specialCareers.politics?.approval??0))}`} actions={[['Run local',()=>gameEngine.campaign(1)],['Run regional',()=>gameEngine.campaign(3)],['Run national',()=>gameEngine.campaign(4)],['Speech',()=>gameEngine.politicalAction('speech')]]} onResult={onResult}/>
 <Path title="Military" stat={`${String(state.specialCareers.military?.branch??'Not enlisted')} · rank ${Number(state.specialCareers.military?.rank??0)}`} actions={[['Enlist Army',()=>gameEngine.enlist('Army')],['Officer path',()=>gameEngine.enlist('Air Service',true)],['Train',()=>gameEngine.militaryTrain()]]} onResult={onResult}/>
 <Path title="Royalty" stat={state.flags.royalBirth?'Born into royal household':'Not currently royal'} actions={[['Perform royal duty',()=>gameEngine.royalDuty()]]} onResult={onResult}/>
 <Path title="Modeling" stat={`Jobs ${Number(state.specialCareers.modeling?.jobs??0)}`} actions={[['Lesson',()=>gameEngine.model('lesson')],['Audition',()=>gameEngine.model('audition')],['Photoshoot',()=>gameEngine.model('photoshoot')],['Runway',()=>gameEngine.model('runway')]]} onResult={onResult}/>
 <Path title="Motorsport" stat={`Skill ${Math.round(Number(state.specialCareers.racing?.skill??0))}`} actions={[['Join',()=>gameEngine.race('join')],['Train',()=>gameEngine.race('train')],['Race',()=>gameEngine.race('race')]]} onResult={onResult}/>
 <Path title="Film directing" stat={`Films ${Number(state.specialCareers.directing?.filmsDirected??0)}`} actions={[['Direct indie film',()=>gameEngine.directFilm(1500000)],['Direct major film',()=>gameEngine.directFilm(25000000)]]} onResult={onResult}/>
 <Path title="Organized crime" stat={`${String(state.specialCareers.crimeOrg?.rank??'Not joined')} · standing ${Math.round(Number(state.specialCareers.crimeOrg?.standing??0))}`} actions={[['Join',()=>gameEngine.joinCrimeOrg()],['Abstract earning job',()=>gameEngine.crimeOrgAction('earn')],['Contribute',()=>gameEngine.crimeOrgAction('contribute')],['Become informant',()=>gameEngine.crimeOrgAction('informant')]]} onResult={onResult}/>
 </div>}
function Path({title,stat,actions,onResult}:{title:string;stat:string;actions:Array<[string,()=>EngineResult]>;onResult:(r:EngineResult)=>void}){return <section className="path-card"><div><h2>{title}</h2><p>{stat}</p></div><div className="action-grid">{actions.map(([label,fn])=><button key={label} onClick={()=>onResult(fn())}>{label}</button>)}</div></section>}
