import { useMemo, useState } from 'react';
import type { EngineResult, GameState, Relationship } from '../types/game';
import { SearchField } from '../components/SearchField';
import { BottomSheet } from '../components/BottomSheet';
import { gameEngine } from '../stores/gameStore';
import { actionAllowed } from '../core/actionEconomy';

export function PeopleScreen({state,onResult}:{state:GameState;onResult:(r:EngineResult)=>void}){const[q,setQ]=useState('');const[selected,setSelected]=useState<Relationship>();
  const rows=useMemo(()=>state.relationships.filter(r=>{const n=state.npcs[r.npcId];return n&&`${n.firstName} ${n.lastName} ${r.type}`.toLowerCase().includes(q.toLowerCase())}).sort((a,b)=>b.score-a.score),[state.relationships,state.npcs,q]);
  const npc=selected?state.npcs[selected.npcId]:undefined;const partner=state.relationships.find(r=>['partner','fiance','spouse'].includes(r.type));const expecting=state.familyPlanning.pregnancy;const canTryChild=actionAllowed(state,{policy:'family.child_attempt'});const canAdopt=actionAllowed(state,{policy:'family.adoption'});const newbornPresent=state.relationships.some(r=>r.type==='child'&&state.npcs[r.npcId]?.alive&&state.npcs[r.npcId]?.age===0);
  return <main className="screen"><div className="screen-title"><div><p className="eyebrow">People</p><h1>Relationships</h1></div><button className="secondary-button" disabled={!actionAllowed(state,{policy:'social.meet'})} onClick={()=>onResult(gameEngine.performActivity('meet_date'))}>Meet someone</button></div><SearchField value={q} onChange={setQ} placeholder="Search people"/>
    <div className="stack">{rows.map(rel=>{const n=state.npcs[rel.npcId]!;return <button className="person-card" key={rel.id} onClick={()=>setSelected(rel)}><div className="npc-monogram">{n.firstName[0]}</div><div className="grow"><strong>{n.firstName} {n.lastName}</strong><small>{rel.type.replace('_',' ')} · age {n.age}{!n.alive?' · deceased':''}</small><div className="mini-meter"><span style={{width:`${rel.score}%`}}/></div></div><strong>{Math.round(rel.score)}</strong></button>})}{rows.length===0&&<div className="empty-card">No matching relationships.</div>}</div>
    {state.character.age>=18&&<section className="action-card"><h2>Family</h2><p>{expecting?`You are expecting ${expecting.expectedChildren===2?'twins':expecting.expectedChildren===3?'triplets':'a child'} next year.`:'Parenthood is persistent: children age, build their own lives, inherit traits, and can continue the dynasty.'}</p><div className="button-row"><button onClick={()=>onResult(gameEngine.haveChild(partner?.npcId,false))} disabled={!partner||!!expecting||!canTryChild||newbornPresent}>{expecting?'Expecting':!canTryChild?'Tried this year':'Try for child'}</button><button onClick={()=>onResult(gameEngine.haveChild(undefined,true))} disabled={!!expecting||!canAdopt||newbornPresent}>{!canAdopt?'Adopted this year':'Adopt'}</button></div></section>}
    <BottomSheet open={!!selected} title={npc?`${npc.firstName} ${npc.lastName}`:'Relationship'} onClose={()=>setSelected(undefined)}>{selected&&npc&&<><div className="sheet-stat-grid"><div><small>Relationship</small><strong>{Math.round(selected.score)}</strong></div><div><small>Compatibility</small><strong>{Math.round(selected.compatibility)}</strong></div><div><small>Age</small><strong>{npc.age}</strong></div><div><small>Status</small><strong>{npc.alive?npc.maritalStatus:'deceased'}</strong></div></div><div className="action-grid">{['conversation','compliment','spend_time','gift','apologize','prank','argue','insult'].map(a=><button key={a} disabled={!npc.alive||!actionAllowed(state,[{policy:'social.npc.total',target:npc.id},{policy:'social.npc.action',target:`${npc.id}:${a}`}])} onClick={()=>onResult(gameEngine.interactWithCharacter(npc.id,a))}>{a.replace('_',' ')}</button>)}</div>{npc.alive&&<div className="sheet-section"><h3>Relationship</h3><div className="action-grid">{selected.type==='friend'&&<button disabled={!actionAllowed(state,{policy:'relationship.milestone',target:npc.id})} onClick={()=>onResult(gameEngine.relationshipAction(npc.id,'ask_out'))}>Ask out</button>}{selected.type==='partner'&&<button disabled={!actionAllowed(state,{policy:'relationship.milestone',target:npc.id})} onClick={()=>onResult(gameEngine.relationshipAction(npc.id,'propose'))}>Propose</button>}{['partner','fiance'].includes(selected.type)&&<button disabled={!actionAllowed(state,{policy:'relationship.milestone',target:npc.id})} onClick={()=>onResult(gameEngine.relationshipAction(npc.id,'marry'))}>Marry</button>}{['partner','fiance'].includes(selected.type)&&<button disabled={!actionAllowed(state,{policy:'relationship.milestone',target:npc.id})} onClick={()=>onResult(gameEngine.relationshipAction(npc.id,'break_up'))}>Break up</button>}{selected.type==='spouse'&&<button disabled={!actionAllowed(state,{policy:'relationship.milestone',target:npc.id})} onClick={()=>onResult(gameEngine.relationshipAction(npc.id,'divorce'))}>Divorce</button>}{selected.type==='ex'&&<button disabled={!actionAllowed(state,{policy:'relationship.milestone',target:npc.id})} onClick={()=>onResult(gameEngine.relationshipAction(npc.id,'reconcile'))}>Reconcile</button>}</div></div>}<div className="sheet-section"><h3>Memories</h3>{npc.memories.slice(-5).reverse().map(m=><p className="memory" key={m.id}>{m.summary}</p>)}{!npc.memories.length&&<p className="muted">No major memories yet.</p>}</div></>}</BottomSheet>
  </main>}
