import type { EngineResult, GameState, Loan } from '../types/game';
import { personalLoanProductById, personalLoanProducts, type PersonalLoanProductDefinition } from '../data/personalLoans';
import { creditInstitutionById } from '../data/creditInstitutions';
import { consumeAction } from '../core/actionEconomy';
import { makeStateId } from '../core/ids';
import { clamp, roundMoney } from '../core/math';
import { getCreditUnderwritingSnapshot, recordCreditInquiry } from './CreditSystem';
import { bankruptcyPreview, declareBankruptcy } from './FinanceSystem';

export interface PersonalLoanOffer {product:PersonalLoanProductDefinition;institutionName:string;eligible:boolean;reason?:string;rate:number;maxApproved:number;annualPayment:number;}

function activeBorrowedPersonalLoans(state:GameState){return state.finances.liabilities.filter(loan=>loan.kind==='personal'&&loan.origin==='borrowed'&&loan.balance>.5);}
function offerTerms(state:GameState,product:PersonalLoanProductDefinition){const snapshot=getCreditUnderwritingSnapshot(state);const scorePremium=clamp((700-snapshot.profile.score)/100,0,1)*.055;const rate=Math.min(.24,product.baseRate+scorePremium);const incomeCap=snapshot.annualIncome*.45;const debtRoom=Math.max(0,(snapshot.annualIncome*product.maxDebtPaymentRatio-snapshot.annualDebtPayments)*product.termYears*.72);const maxApproved=roundMoney(Math.max(0,Math.min(product.maxAmount,incomeCap,debtRoom)));return{snapshot,rate,maxApproved};}
function declineReason(state:GameState,product:PersonalLoanProductDefinition,maxApproved:number){const snapshot=getCreditUnderwritingSnapshot(state);if(state.character.age<product.minAge)return`Available starting at age ${product.minAge}.`;if(activeBorrowedPersonalLoans(state).length>=2)return'You already have the maximum number of active personal-loan contracts.';if(snapshot.profile.score<product.minCreditScore)return`Your credit profile is below this lender's ${product.minCreditScore} threshold.`;if(snapshot.annualIncome<product.minAnnualIncome)return`This lender requires at least ${product.minAnnualIncome.toLocaleString()} in annual income.`;if(snapshot.debtPaymentRatio>product.maxDebtPaymentRatio)return'Your existing required debt payments are too high relative to income.';if(snapshot.yearsSinceBankruptcy!==undefined&&snapshot.yearsSinceBankruptcy<product.bankruptcyRecoveryYears)return`This lender requires ${product.bankruptcyRecoveryYears} years of recovery after bankruptcy.`;if(maxApproved<product.minAmount)return'Your current income and debt obligations do not support this lender’s minimum loan amount.';return undefined;}
export function getPersonalLoanOffers(state:GameState):PersonalLoanOffer[]{return personalLoanProducts.map(product=>{const terms=offerTerms(state,product);const reason=declineReason(state,product,terms.maxApproved);const annualPayment=roundMoney(terms.maxApproved<=0?0:terms.rate>0?terms.maxApproved*terms.rate/(1-Math.pow(1+terms.rate,-product.termYears)):terms.maxApproved/product.termYears);return{product,institutionName:creditInstitutionById[product.institutionId]?.name??product.institutionId,eligible:!reason,reason,rate:terms.rate,maxApproved:terms.maxApproved,annualPayment};}).filter(offer=>state.character.age>=Math.max(16,offer.product.minAge-2));}
export function applyForPersonalLoan(state:GameState,productId:string,rawAmount:number):EngineResult{
  const product=personalLoanProductById[productId];if(!product)return{success:false,messages:[{text:'That personal-loan product is unavailable.'}]};const terms=offerTerms(state,product);const reason=declineReason(state,product,terms.maxApproved);const amount=roundMoney(Math.floor(rawAmount/100)*100);const action=consumeAction(state,[{policy:'credit.application.total'},{policy:'credit.application.product',target:product.id}]);if(!action.allowed)return{success:false,messages:[{text:action.message??'You cannot make another formal credit application this year.'}]};if(reason){recordCreditInquiry(state,{institutionId:product.institutionId,productId:product.id,outcome:'declined',reason});return{success:false,stateChanges:['creditInquiry'],messages:[{text:reason}]};}if(amount<product.minAmount||amount>terms.maxApproved){const amountReason=`Choose an amount from ${product.minAmount.toLocaleString()} to ${Math.floor(terms.maxApproved).toLocaleString()}.`;recordCreditInquiry(state,{institutionId:product.institutionId,productId:product.id,outcome:'declined',reason:amountReason});return{success:false,stateChanges:['creditInquiry'],messages:[{text:amountReason}]};}
  const annualPayment=roundMoney(terms.rate>0?amount*terms.rate/(1-Math.pow(1+terms.rate,-product.termYears)):amount/product.termYears);const loan:Loan={id:makeStateId(state,'loan'),kind:'personal',principal:amount,balance:amount,annualRate:terms.rate,annualPayment,remainingYears:product.termYears,autoPay:true,origin:'borrowed',institutionId:product.institutionId,productId:product.id};state.finances.liabilities.push(loan);state.finances.cash=roundMoney(state.finances.cash+amount);recordCreditInquiry(state,{institutionId:product.institutionId,productId:product.id,outcome:'approved'});state.timeline.push({id:makeStateId(state,'timeline'),year:state.currentYear,age:state.character.age,category:'money',importance:2,text:`You borrowed ${Math.round(amount).toLocaleString()} through ${product.name}.`,moneyDelta:amount,detail:`${(terms.rate*100).toFixed(1)}% APR · ${product.termYears}-year term · annual payment ${Math.round(annualPayment).toLocaleString()}.`});return{success:true,stateChanges:['cash','financingLiability','creditInquiry'],messages:[{text:`Loan funded. ${Math.round(amount).toLocaleString()} was added to cash; annual auto-pay starts on.`}]};
}
export function getBankruptcyDecision(state:GameState){return bankruptcyPreview(state);}
export function fileVoluntaryBankruptcy(state:GameState):EngineResult{const preview=bankruptcyPreview(state);if(!preview.eligible)return{success:false,messages:[{text:preview.reason??'Bankruptcy is not currently available.'}]};const ok=declareBankruptcy(state,'voluntary');return ok?{success:true,stateChanges:['cash','financingLiability','credit','bankruptcy'],messages:[{text:`Bankruptcy completed. ${Math.round(preview.dischargeableDebt).toLocaleString()} of eligible unsecured debt was discharged; secured and student obligations remain.`}]}:{success:false,messages:[{text:'There is no eligible unsecured debt to discharge.'}]};}
export function migratePersonalBorrowingState(state:GameState){for(const loan of state.finances?.liabilities??[]){if(loan.kind!=='personal')continue;loan.autoPay=loan.autoPay!==false;loan.origin=loan.origin??'hardship';if(!Number.isFinite(loan.prepaidThroughAge))delete loan.prepaidThroughAge;}}
