import { useMemo, useRef, useState } from 'react';
import type { GameState } from '../types/game';
import { BottomSheet } from './BottomSheet';
import { SearchField } from './SearchField';
import { achievements, challenges } from '../data/achievements';
import { gameEngine } from '../stores/gameStore';
import { exportSave, importSave } from '../services/SaveSystem';
import { formatMoney } from '../core/format';

export function MetaSheet({open,onClose,onNewLife}:{open:boolean;onClose:()=>void;onNewLife:()=>void}){const state=gameEngine.getState();const[tab,setTab]=useState<'progress'|'lives'|'settings'|'debug'>('progress');const[q,setQ]=useState('');const fileRef=useRef<HTMLInputElement>(null);const filteredAchievements=useMemo(()=>achievements.filter(a=>`${a.name} ${a.description} ${a.category}`.toLowerCase().includes(q.toLowerCase())),[q]);const filteredChallenges=useMemo(()=>challenges.filter(c=>`${c.title} ${c.description}`.toLowerCase().includes(q.toLowerCase())),[q]);
 const download=()=>{const blob=new Blob([exportSave(gameEngine.getState())],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`everthread-${state.character.firstName.toLowerCase()}-age-${state.character.age}.json`;a.click();URL.revokeObjectURL(url);};
 const upload=async(file?:File)=>{if(!file)return;try{const text=await file.text();gameEngine.replaceState(importSave(text));onClose();}catch(err){alert(err instanceof Error?err.message:'Could not import save.');}};
 return <BottomSheet open={open} title="Everthread" onClose={onClose} wide><div className="segmented segmented--scroll"><button className={tab==='progress'?'active':''} onClick={()=>setTab('progress')}>Progress</button><button className={tab==='lives'?'active':''} onClick={()=>setTab('lives')}>Past lives</button><button className={tab==='settings'?'active':''} onClick={()=>setTab('settings')}>Settings</button>{(state.flags.sandbox||state.flags.debugEnabled)&&<button className={tab==='debug'?'active':''} onClick={()=>setTab('debug')}>Sandbox</button>}</div>
 {tab==='progress'&&<><SearchField value={q} onChange={setQ} placeholder="Search achievements & challenges"/><section className="sheet-section"><div className="section-heading"><h3>Challenges</h3><span>{state.challenges.filter(c=>c.completed).length} complete</span></div><div className="progress-list">{filteredChallenges.map(c=>{const p=state.challenges.find(x=>x.id===c.id);return <article key={c.id} className={`progress-card ${p?.completed?'complete':''}`}><div><strong>{c.title}</strong><small>{c.description}</small><em>{c.difficulty} · reward: {c.reward}</em></div>{p?.completed?<b>✓</b>:p?.activated?<span>{Math.round((p.progress??0)*100)}%</span>:<button onClick={()=>gameEngine.activateChallenge(c.id)}>Start</button>}</article>})}</div></section><section className="sheet-section"><div className="section-heading"><h3>Achievements</h3><span>{state.achievements.filter(a=>a.completed).length}/{achievements.length}</span></div><div className="progress-list">{filteredAchievements.map(a=>{const p=state.achievements.find(x=>x.id===a.id);return <article className={`progress-card ${p?.completed?'complete':''}`} key={a.id}><div><strong>{a.name}</strong><small>{a.description}</small><em>{a.category}</em></div><span>{p?.completed?'✓':`${Math.round((p?.progress??0)*100)}%`}</span></article>})}</div></section></>}
 {tab==='lives'&&<><section className="legacy-card"><p className="eyebrow">Family legacy</p><h2>Generation {state.legacy.generation}</h2><div className="finance-grid"><div><small>Years simulated</small><strong>{state.legacy.totalYearsSimulated}</strong></div><div><small>Peak family wealth</small><strong>{formatMoney(state.legacy.totalFamilyWealth)}</strong></div><div><small>Completed lives</small><strong>{state.completedLives.length}</strong></div><div><small>Legacy rewards</small><strong>{state.legacy.accountCollectibleIds.length}</strong></div></div></section><div className="stack">{state.completedLives.map(l=><details className="past-life" key={l.id}><summary><span><strong>{l.character.firstName} {l.character.lastName}</strong><small>Age {l.ageAtDeath} · {l.career??'No primary career'}</small></span><b>{formatMoney(l.netWorth)}</b></summary><p>{l.epitaph}</p><p>Cause: {l.cause}</p></details>)}{!state.completedLives.length&&<p className="empty-card">No completed lives yet.</p>}</div></>}
 {tab==='settings'&&<Settings state={state} download={download} upload={()=>fileRef.current?.click()} onNewLife={onNewLife}/>}<input ref={fileRef} hidden type="file" accept="application/json,.json" onChange={e=>upload(e.target.files?.[0])}/>
 {tab==='debug'&&<Debug state={state}/>}</BottomSheet>}

function Settings({state,download,upload,onNewLife}:{state:GameState;download:()=>void;upload:()=>void;onNewLife:()=>void}){const set=(patch:Partial<GameState['settings']>)=>gameEngine.updateSettings(patch);return <div className="settings-list"><label className="form-field"><span>Theme</span><select value={state.settings.theme} onChange={e=>set({theme:e.target.value as GameState['settings']['theme']})}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label><label className="form-field"><span>Accent color</span><input type="color" value={state.settings.accent} onChange={e=>set({accent:e.target.value})}/></label><label className="form-field"><span>Text size · {Math.round(state.settings.textScale*100)}%</span><input type="range" min="0.9" max="1.3" step="0.05" value={state.settings.textScale} onChange={e=>set({textScale:Number(e.target.value)})}/></label>{([['sound','Sound'],['haptics','Haptics'],['animations','Animations'],['minigames','Minigames'],['profanityFilter','Profanity filter'],['autoSave','Auto-save'],['highContrast','High contrast'],['reducedMotion','Reduced motion'],['notifications','Optional notifications']] as const).map(([key,label])=><label className="toggle-row" key={key}><span><strong>{label}</strong></span><input type="checkbox" checked={state.settings[key]} onChange={e=>set({[key]:e.target.checked})}/></label>)}<div className="sheet-section"><h3>Data</h3><div className="action-grid"><button onClick={download}>Export save JSON</button><button onClick={upload}>Import save JSON</button><button onClick={onNewLife}>Create another life</button></div></div></div>}
function Debug({state}:{state:GameState}){const[age,setAge]=useState(state.character.age);const[money,setMoney]=useState(state.finances.cash);return <div className="form-stack"><p className="warning-card">Sandbox tools deliberately mark this save as nonstandard. They are useful for testing systems and content.</p><label className="form-field"><span>Age</span><input type="number" value={age} onChange={e=>setAge(Number(e.target.value))}/></label><label className="form-field"><span>Cash</span><input type="number" value={money} onChange={e=>setMoney(Number(e.target.value))}/></label><button onClick={()=>gameEngine.debugPatch({age,money})}>Apply values</button><button onClick={()=>gameEngine.forceDeath()}>Force death</button><div className="code-card"><small>RNG seed</small><code>{state.seed}</code><small>RNG counter</small><code>{state.rngCounter}</code></div>{state.flags.rewindEnabled&&<><h3>Yearly snapshots</h3><div className="action-grid">{state.yearlySnapshots.slice(-10).reverse().map(s=><button key={s.age} onClick={()=>gameEngine.rewind(s.age)}>Age {s.age}</button>)}</div></>}</div>}
