import { useState } from 'react';
import { gameEngine } from '../stores/gameStore';
import { countries } from '../data/countries';
import type { GenderIdentity, Orientation, Sex } from '../types/game';

type SliderDefinition = { label: string; value: number; setValue: (value: number) => void };

export function NewLifeForm({onCreated}:{onCreated:()=>void}){const[firstName,setFirst]=useState('');const[lastName,setLast]=useState('');const[countryId,setCountry]=useState('us');const[sex,setSex]=useState<Sex>('female');const[gender,setGender]=useState<GenderIdentity>('woman');const[orientation,setOrientation]=useState<Orientation>('straight');const[sandbox,setSandbox]=useState(false);const[advanced,setAdvanced]=useState(false);const[intelligence,setIntelligence]=useState(60);const[appearance,setAppearance]=useState(60);const[health,setHealth]=useState(80);
 const create=()=>{gameEngine.newLife({firstName:firstName||undefined,lastName:lastName||undefined,countryId,sex,genderIdentity:gender,orientation,sandbox,rewindEnabled:sandbox,advanced:advanced?{intelligence,appearance,health}:undefined});onCreated();};return <div className="form-stack"><div className="two-col"><label className="form-field"><span>First name</span><input value={firstName} onChange={e=>setFirst(e.target.value)} placeholder="Random if blank"/></label><label className="form-field"><span>Last name</span><input value={lastName} onChange={e=>setLast(e.target.value)} placeholder="Random if blank"/></label></div><label className="form-field"><span>Country</span><select value={countryId} onChange={e=>setCountry(e.target.value)}>{countries.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><div className="two-col"><label className="form-field"><span>Sex</span><select value={sex} onChange={e=>setSex(e.target.value as Sex)}><option>female</option><option>male</option><option>intersex</option></select></label><label className="form-field"><span>Gender</span><select value={gender} onChange={e=>setGender(e.target.value as GenderIdentity)}><option value="woman">woman</option><option value="man">man</option><option value="nonbinary">nonbinary</option><option value="other">other</option></select></label></div><label className="form-field"><span>Orientation</span><select value={orientation} onChange={e=>setOrientation(e.target.value as Orientation)}>{['straight','gay','lesbian','bisexual','pansexual','asexual'].map(o=><option key={o}>{o}</option>)}</select></label><label className="toggle-row"><span><strong>Advanced creation</strong><small>Influence normally hidden starting stats.</small></span><input type="checkbox" checked={advanced} onChange={e=>setAdvanced(e.target.checked)}/></label>{advanced&&<div className="slider-stack">{([{label:'Intelligence',value:intelligence,setValue:setIntelligence},{label:'Appearance',value:appearance,setValue:setAppearance},{label:'Health',value:health,setValue:setHealth}] satisfies SliderDefinition[]).map(({label,value,setValue})=><label key={label}><span>{label}: {value}</span><input type="range" min="10" max="100" value={value} onChange={e=>setValue(Number(e.target.value))}/></label>)}</div>}<label className="toggle-row"><span><strong>Sandbox mode</strong><small>Enables rewind and future cheat/customization controls.</small></span><input type="checkbox" checked={sandbox} onChange={e=>setSandbox(e.target.checked)}/></label><div className="button-row"><button className="full-button" onClick={create}>Create life</button><button className="secondary-button" onClick={()=>{gameEngine.newLife();onCreated();}}>Fully random</button></div></div>}
