import { useState } from 'react';
import type { EngineResult, GameState, Npc, SocialWorld } from '../types/game';
import { BottomSheet } from './BottomSheet';
import { gameEngine } from '../stores/gameStore';
import { actionAllowed } from '../core/actionEconomy';
import { formatMoney } from '../core/format';
import { specialCareerWorldKind, specialCareerWorldView, type SpecialCareerWorldView } from '../systems/SpecialCareerEcosystemSystem';
import { screenCareerOffer } from '../systems/ScreenCareerCycleSystem';
import { musicCatalog, musicPartnershipOffer } from '../systems/MusicCareerCycleSystem';
import { modelingAgencyOffer, modelingCampaignHistory } from '../systems/ModelingCareerCycleSystem';
import { racingContractOffer, racingSeasonHistory } from '../systems/RacingCareerCycleSystem';
import { combatCareerWorldView } from '../systems/CombatCareerWorldSystem';
import { militaryCareerWorldView } from '../systems/MilitaryCareerWorldSystem';
import { politicsCareerWorldView, politicsOfficeLabel } from '../systems/PoliticsCareerWorldSystem';
import type { SpecialCareerWorldKind } from '../systems/SpecialCareerWorldSystem';
import { careerActionVfx, type ActionResultHandler, type ActionVfxRequest } from '../core/actionVfx';
import { persistentCareerWorldKind, persistentCareerWorldLabel, persistentCareerWorlds, type PersistentCareerWorldKind } from '../systems/CareerWorldCatalogSystem';

const KIND_LABELS:Record<SpecialCareerWorldKind,string>={acting:'Acting production',music:'Music collective',sports:'Professional team',modeling:'Modeling network',racing:'Race team',directing:'Film production'};
type SupplementalWorldKind=Extract<PersistentCareerWorldKind,'combat'|'military'|'politics'>;
type CareerTrack=Record<string,number|string|boolean>;
function careerTrack(state:GameState,kind:SpecialCareerWorldKind){return (state.specialCareers[kind]??{}) as CareerTrack;}
function person(state:GameState,id?:string):Npc|undefined{return id?state.npcs[id]:undefined;}
function relationScore(state:GameState,id?:string){return id?state.relationships.find(rel=>rel.npcId===id)?.score:undefined;}
function interactionAllowed(state:GameState,id:string|undefined,action:string){return Boolean(id)&&actionAllowed(state,[{policy:'social.npc.total',target:id!},{policy:'social.npc.action',target:`${id}:${action}`}]);}
function resolvedImpact(world:SocialWorld){return world.groups.find(group=>group.kind.endsWith(':resolved'))?.prestige;}
function worldSort(a:SocialWorld,b:SocialWorld){return Number(b.active)-Number(a.active)||b.startedAge-a.startedAge||b.id.localeCompare(a.id);}
function supplementalWorldKind(world:SocialWorld):SupplementalWorldKind|undefined{const kind=persistentCareerWorldKind(world);return kind==='combat'||kind==='military'||kind==='politics'?kind:undefined;}
function careerWorldLabel(world:SocialWorld){const kind=persistentCareerWorldKind(world);return kind?persistentCareerWorldLabel(kind):'Career world';}
function activeMemberCount(state:GameState,world:SocialWorld){return world.members.filter(member=>member.leftAge===undefined&&state.npcs[member.npcId]?.alive).length;}

export function SpecialCareerWorldPanel({state,onResult}:{state:GameState;onResult:ActionResultHandler}){
  const[open,setOpen]=useState(false);const worlds=persistentCareerWorlds(state).slice().sort(worldSort);const active=worlds.filter(world=>world.active);const history=worlds.filter(world=>!world.active).slice(0,12);
  const actingOffer=screenCareerOffer(state,'acting');const directingOffer=screenCareerOffer(state,'directing');const musicOffer=musicPartnershipOffer(state);const modelingOffer=modelingAgencyOffer(state);const racingOffer=racingContractOffer(state);const offerCount=Number(Boolean(actingOffer))+Number(Boolean(directingOffer))+Number(Boolean(musicOffer))+Number(Boolean(modelingOffer))+Number(Boolean(racingOffer));
  const actingActive=active.some(world=>specialCareerWorldKind(world)==='acting');const directingActive=active.some(world=>specialCareerWorldKind(world)==='directing');const hasContent=worlds.length>0||offerCount>0;
  const acting=careerTrack(state,'acting');const directing=careerTrack(state,'directing');const music=careerTrack(state,'music');const modeling=careerTrack(state,'modeling');const racing=careerTrack(state,'racing');const catalog=musicCatalog(state).slice(0,6);const modelHistory=modelingCampaignHistory(state).slice(0,6);const raceHistory=racingSeasonHistory(state).slice(0,6);const racingPathway=racing.racingPathway===true||racing.active===true||racing.freeAgent===true||racing.retired===true||Number(racing.seasons??0)>0;
  return <>
    <section className="action-card"><div className="section-heading"><div><p className="eyebrow">Persistent career worlds</p><h2>{active.length?`${active.length} active ${active.length===1?'ecosystem':'ecosystems'}`:'Career ecosystem'}</h2></div><span>{offerCount?`${offerCount} offer${offerCount===1?'':'s'}`:`${worlds.length} total`}</span></div>
      {active.length?<p className="muted">{active.slice(0,3).map(world=>world.name).join(' · ')}{active.length>3?` · +${active.length-3} more`:''}. Recurring people and professional relationships feed directly into career outcomes.</p>:offerCount?<p className="muted">Your recent work generated a follow-up opportunity. Offers expire with age and still respect the normal career action limits.</p>:<p className="muted">Professional productions, teams, gyms, service postings, political offices, agencies, and race programs can become persistent career worlds.</p>}
      <div className="button-row"><button disabled={!hasContent} onClick={()=>setOpen(true)}>{offerCount?'Review career offers':active.length?'Open career worlds':'View career history'}</button></div></section>
    <BottomSheet open={open} title="Career worlds" onClose={()=>setOpen(false)} wide>
      {offerCount>0&&<div className="sheet-section"><h3>Pending offers</h3>
        {actingOffer&&<article className="school-group-card joined"><div><strong>Acting offer · {actingOffer.role}</strong><small>From {actingOffer.sourceProject} · {formatMoney(actingOffer.pay??0)} · expires after age {actingOffer.expiresAge}</small></div><div className="school-group-actions"><button disabled={actingActive||!actionAllowed(state,{policy:'special.audition'})} onClick={()=>onResult(gameEngine.actingAudition())}>Accept role</button></div></article>}
        {directingOffer&&<article className="school-group-card joined"><div><strong>Studio-backed directing offer</strong><small>From {directingOffer.sourceProject} · {formatMoney(directingOffer.budget??0)} budget · {formatMoney(directingOffer.fee??0)} fee · expires after age {directingOffer.expiresAge}</small></div><div className="school-group-actions"><button disabled={directingActive||!actionAllowed(state,{policy:'special.direct_film'})} onClick={()=>onResult(gameEngine.directFilm(directingOffer.budget??1500000))}>Accept film</button></div></article>}
        {musicOffer&&<article className="school-group-card joined"><div><strong>Music distribution offer · {musicOffer.partner}</strong><small>From {musicOffer.sourceRelease} · {formatMoney(musicOffer.advance)} advance · {Math.round(musicOffer.royaltyShare*100)}% royalty share · {Math.round((musicOffer.reach-1)*100)}% reach boost · expires after age {musicOffer.expiresAge}</small></div><div className="school-group-actions"><button disabled={!actionAllowed(state,{policy:'special.music_business'})} onClick={()=>onResult(gameEngine.musicPartnership('accept'),{primary:careerActionVfx('music'),derive:true})}>Accept partnership</button><button className="secondary-button" disabled={!actionAllowed(state,{policy:'special.music_business'})} onClick={()=>onResult(gameEngine.musicPartnership('decline'))}>Decline</button></div></article>}
        {modelingOffer&&<article className="school-group-card joined"><div><strong>{modelingOffer.kind==='renewal'?'Agency renewal':'Modeling representation'} · {modelingOffer.agency}</strong><small>{modelingOffer.years} years · {Math.round(modelingOffer.commission*100)}% commission · {Math.round((modelingOffer.reach-1)*100)}% booking-reach boost · expires after age {modelingOffer.expiresAge}</small></div><div className="school-group-actions"><button disabled={!actionAllowed(state,{policy:'special.model.business'})} onClick={()=>onResult(gameEngine.modelingAgency('accept'),{primary:careerActionVfx('modeling'),derive:true})}>Accept contract</button><button className="secondary-button" disabled={!actionAllowed(state,{policy:'special.model.business'})} onClick={()=>onResult(gameEngine.modelingAgency('decline'))}>Decline</button></div></article>}
        {racingOffer&&<article className="school-group-card joined"><div><strong>{racingOffer.kind==='renewal'?'Racing renewal':'Racing team offer'} · {racingOffer.team}</strong><small>{racingOffer.years} years · {formatMoney(racingOffer.salary)}/season · expires after age {racingOffer.expiresAge}</small></div><div className="school-group-actions"><button disabled={!actionAllowed(state,{policy:'special.racing_business'})} onClick={()=>onResult(gameEngine.racingContract('accept'),{primary:careerActionVfx('racing'),derive:true})}>Accept contract</button><button className="secondary-button" disabled={!actionAllowed(state,{policy:'special.racing_business'})} onClick={()=>onResult(gameEngine.racingContract('decline'))}>Decline</button></div></article>}
      </div>}
      {active.length>0&&<div className="sheet-section"><h3>Active ecosystems</h3>{active.map(world=><UnifiedCareerWorldCard key={world.id} state={state} world={world} onResult={onResult}/>)}</div>}
      {catalog.length>0&&<div className="sheet-section"><h3>Recent music catalog</h3>{catalog.map(entry=><p className="memory" key={`${entry.slot}-${entry.title}-${entry.launchAge}`}><strong>{entry.title}</strong> · {entry.kind} · age {entry.launchAge} · {entry.reception} · launch {entry.launchStreams.toLocaleString()} · lifetime {entry.lifetimeStreams.toLocaleString()} streams</p>)}</div>}
      {modelHistory.length>0&&<div className="sheet-section"><h3>Recent modeling campaigns</h3>{modelHistory.map(entry=><p className="memory" key={`${entry.slot}-${entry.title}-${entry.completedAge}`}><strong>{entry.title}</strong> · {entry.kind} · completed age {entry.completedAge} · {entry.reception} · {Math.round(entry.score)}/100 · net {formatMoney(entry.netPay)}</p>)}</div>}
      {raceHistory.length>0&&<div className="sheet-section"><h3>Recent racing seasons</h3>{raceHistory.map(entry=><p className="memory" key={`${entry.slot}-${entry.age}-${entry.team}`}><strong>{entry.team}</strong> · age {entry.age} · P{entry.championshipPosition} · {entry.wins} win{entry.wins===1?'':'s'} · {entry.podiums} podium{entry.podiums===1?'':'s'} · {entry.points} points · {entry.outcome}</p>)}</div>}
      {racingPathway&&<div className="sheet-section"><h3>Racing career</h3><p className="memory">Status: {racing.retired===true?'retired':racing.freeAgent===true?'free agent':racing.contractActive===true?`contracted to ${String(racing.teamName??racing.worldName??'team')}`:'racing pathway'} · {Number(racing.seasons??0)} recorded season{Number(racing.seasons??0)===1?'':'s'} · {Number(racing.titles??0)} championship{Number(racing.titles??0)===1?'':'s'}.</p>{racing.contractActive===true&&<p className="memory">Contract: {Number(racing.contractRemaining??0)} year{Number(racing.contractRemaining??0)===1?'':'s'} remaining · {formatMoney(Number(racing.salary??0))}/season.</p>}{racing.seasonActive===true&&<p className="memory">Season underway: {String(racing.currentSeasonTeam??racing.teamName??'team')} · {Number(racing.currentSeasonRaces??0)} rounds. Championship results and earnings resolve on the next Age Up.</p>}{racing.lastSeasonAge&&<p className="memory">Latest season: P{Number(racing.lastChampionshipPosition??20)} · {Number(racing.lastSeasonWins??0)} wins · {Number(racing.lastSeasonPodiums??0)} podiums · score {Math.round(Number(racing.lastSeasonScore??0))}/100 · pressure {Math.round(Number(racing.teamPressure??0))}/100.</p>}<div className="button-row">{racing.retired!==true&&<button disabled={!actionAllowed(state,{policy:'special.training',target:'racing'})} onClick={()=>onResult(gameEngine.race('train'))}>Train</button>}{racing.freeAgent===true&&racing.retired!==true&&!racingOffer&&<button disabled={!actionAllowed(state,{policy:'special.racing_contract_seek'})} onClick={()=>onResult(gameEngine.racingContract('seek'))}>Seek team contract</button>}{racing.retired!==true&&<button className="secondary-button" disabled={racing.seasonActive===true} onClick={()=>onResult(gameEngine.racingRetire())}>Retire from racing</button>}</div></div>}
      {(acting.lastProjectName||directing.lastProjectName||music.lastTourName||modeling.lastCampaignTitle)&&<div className="sheet-section"><h3>Latest major releases & tours</h3>
        {acting.lastProjectName&&<p className="memory"><strong>{String(acting.lastProjectName)}</strong> · {String(acting.lastProjectRole??'role')} · {String(acting.lastProjectReception??'released')} · impact {Math.round(Number(acting.lastProjectScore??0))}/100{Number(acting.lastProjectBonus??0)>0?` · bonus ${formatMoney(Number(acting.lastProjectBonus))}`:''}</p>}
        {directing.lastProjectName&&<p className="memory"><strong>{String(directing.lastProjectName)}</strong> · {String(directing.lastProjectReception??'released')} · impact {Math.round(Number(directing.lastProjectScore??0))}/100 · box office {formatMoney(Number(directing.lastBoxOffice??0))}</p>}
        {music.lastTourName&&<p className="memory"><strong>{String(music.lastTourName)}</strong> · {String(music.lastTourScale??'tour')} · {Number(music.lastTourShows??0)} shows · performance {Math.round(Number(music.lastTourScore??0))}/100 · net {formatMoney(Number(music.lastTourNet??0))}</p>}
        {modeling.lastCampaignTitle&&<p className="memory"><strong>{String(modeling.lastCampaignTitle)}</strong> · {String(modeling.lastCampaignKind??'campaign')} · {String(modeling.lastCampaignReception??'completed')} · performance {Math.round(Number(modeling.lastCampaignScore??0))}/100 · net {formatMoney(Number(modeling.lastCampaignNet??0))}</p>}
      </div>}
      {history.length>0&&<div className="sheet-section"><h3>Career history</h3>{history.map(world=>{const impact=resolvedImpact(world);return <p className="memory" key={world.id}><strong>{world.name}</strong> · {careerWorldLabel(world)} · ages {world.startedAge}–{world.endedAge??state.character.age}{impact!==undefined?` · impact ${Math.round(impact)}/100`:''}</p>})}</div>}
      {!hasContent&&<p className="muted">No special-career worlds or offers have been created in this life yet.</p>}
    </BottomSheet>
  </>;
}

function UnifiedCareerWorldCard({state,world,onResult}:{state:GameState;world:SocialWorld;onResult:ActionResultHandler}){
  if(specialCareerWorldKind(world))return <CareerWorldCard state={state} world={world} onResult={onResult}/>;
  return <SupplementalCareerWorldCard state={state} world={world} onResult={onResult}/>;
}

function SupplementalCareerWorldCard({state,world,onResult}:{state:GameState;world:SocialWorld;onResult:ActionResultHandler}){
  const kind=supplementalWorldKind(world);if(!kind)return null;
  const interact=(npc:Npc|undefined,action:string,vfx?:ActionVfxRequest)=>{if(npc)onResult(gameEngine.interactWithCharacter(npc.id,action),vfx??{derive:true});};
  if(kind==='combat'){
    const view=combatCareerWorldView(state,world);if(!view)return null;const coach=person(state,view.coachNpcId);const partner=person(state,view.trainingNpcIds[0]);const rival=person(state,view.rivalNpcIds[0]);
    return <article className="school-group-card joined"><div className="section-heading"><div><p className="eyebrow">{persistentCareerWorldLabel(kind)}</p><h3>{world.name}</h3></div><span>{activeMemberCount(state,world)} people</span></div><div className="sheet-stat-grid"><div><small>Coach support</small><strong>{Math.round(view.coachSupport)}</strong></div><div><small>Chemistry</small><strong>{Math.round(view.trainingChemistry)}</strong></div><div><small>Prestige</small><strong>{Math.round(view.prestige)}</strong></div><div><small>Rivalry</small><strong>{Math.round(view.rivalPressure)}</strong></div></div><p className="muted">{coach?`Head coach: ${coach.firstName} ${coach.lastName} (${Math.round(relationScore(state,coach.id)??0)})`:'No current head coach'}{rival?` · Rival: ${rival.firstName} ${rival.lastName}`:''}</p><div className="button-row"><button disabled={!partner||!interactionAllowed(state,partner.id,'spend_time')} onClick={()=>interact(partner,'spend_time',{primary:'chemistryGain',derive:true,suppressDerived:['relationshipGain']})}>Build chemistry</button><button disabled={!coach||!interactionAllowed(state,coach.id,'conversation')} onClick={()=>interact(coach,'conversation')}>Talk to coach</button>{rival&&<button className="secondary-button" disabled={!interactionAllowed(state,rival.id,'conversation')} onClick={()=>interact(rival,'conversation')}>Talk to rival</button>}</div></article>;
  }
  if(kind==='military'){
    const view=militaryCareerWorldView(state,world);if(!view)return null;const commander=person(state,view.commanderNpcId);const peer=person(state,view.peerNpcIds[0]);const support=person(state,view.supportNpcIds[0]);const standing=Math.round(Number(state.specialCareers.military?.serviceStanding??0));
    return <article className="school-group-card joined"><div className="section-heading"><div><p className="eyebrow">{persistentCareerWorldLabel(kind)}</p><h3>{world.name}</h3></div><span>{activeMemberCount(state,world)} people</span></div><div className="sheet-stat-grid"><div><small>Standing</small><strong>{standing||'—'}</strong></div><div><small>Command</small><strong>{Math.round(view.commandSupport)}</strong></div><div><small>Cohesion</small><strong>{Math.round(view.unitCohesion)}</strong></div><div><small>Prestige</small><strong>{Math.round(view.prestige)}</strong></div></div><p className="muted">{commander?`Commander: ${commander.firstName} ${commander.lastName} (${Math.round(relationScore(state,commander.id)??0)})`:'No current commander'}</p><div className="button-row"><button disabled={!peer||!interactionAllowed(state,peer.id,'spend_time')} onClick={()=>interact(peer,'spend_time')}>Connect with peer</button><button disabled={!commander||!interactionAllowed(state,commander.id,'conversation')} onClick={()=>interact(commander,'conversation')}>Talk to commander</button>{support&&<button className="secondary-button" disabled={!interactionAllowed(state,support.id,'conversation')} onClick={()=>interact(support,'conversation')}>Talk to specialist</button>}</div></article>;
  }
  const view=politicsCareerWorldView(state,world);if(!view)return null;const chief=person(state,view.chiefStaffNpcId);const ally=person(state,view.coalitionNpcIds[0]);const opponent=person(state,view.opponentNpcId);const officeLevel=view.officeLevel;
  return <article className="school-group-card joined"><div className="section-heading"><div><p className="eyebrow">{politicsOfficeLabel(officeLevel)}</p><h3>{world.name}</h3></div><span>{activeMemberCount(state,world)} people</span></div><div className="sheet-stat-grid"><div><small>Standing</small><strong>{Math.round(view.politicalStanding)}</strong></div><div><small>Staff</small><strong>{Math.round(view.staffSupport)}</strong></div><div><small>Coalition</small><strong>{Math.round(view.coalitionSupport)}</strong></div><div><small>Opposition</small><strong>{Math.round(view.oppositionPressure)}</strong></div></div><p className="muted">{chief?`Chief of staff: ${chief.firstName} ${chief.lastName} (${Math.round(relationScore(state,chief.id)??0)})`:'No current chief of staff'}{opponent?` · Opposition: ${opponent.firstName} ${opponent.lastName}`:''}</p><div className="button-row"><button disabled={!ally||!interactionAllowed(state,ally.id,'spend_time')} onClick={()=>interact(ally,'spend_time')}>Build coalition</button><button disabled={!chief||!interactionAllowed(state,chief.id,'conversation')} onClick={()=>interact(chief,'conversation')}>Talk to chief</button>{opponent&&<button className="secondary-button" disabled={!interactionAllowed(state,opponent.id,'conversation')} onClick={()=>interact(opponent,'conversation')}>Talk to opponent</button>}</div></article>;
}

function CareerWorldCard({state,world,onResult}:{state:GameState;world:SocialWorld;onResult:ActionResultHandler}){
  const view=specialCareerWorldView(state,world) as SpecialCareerWorldView;const career=careerTrack(state,view.kind);const leader=person(state,view.leaderNpcId);const rival=person(state,view.rivalNpcId);const peer=person(state,view.peerNpcId);const momentum=Math.round(Number(career.careerMomentum??0));const awards=Number(career.awards??0);const scandals=Number(career.scandals??0);const project=view.kind==='acting'||view.kind==='directing';const interact=(npc:Npc|undefined,action:string,vfx?:ActionVfxRequest)=>{if(npc)onResult(gameEngine.interactWithCharacter(npc.id,action),vfx??{derive:true});};const contractRemaining=Number(career.contractRemaining??career.contractYears??0);const salary=Number(career.salary??0);
  const modelOffer=view.kind==='modeling'?modelingAgencyOffer(state):undefined;
  return <article className="school-group-card joined"><div className="section-heading"><div><p className="eyebrow">{KIND_LABELS[view.kind]}</p><h3>{world.name}</h3></div><span>{view.memberCount} people</span></div>
    <div className="sheet-stat-grid">{!project&&<div><small>Momentum</small><strong>{momentum||'—'}</strong></div>}<div><small>Chemistry</small><strong>{Math.round(view.chemistry)}</strong></div><div><small>Prestige</small><strong>{Math.round(view.prestige)}</strong></div><div><small>Rivalry</small><strong>{Math.round(view.rivalry)}</strong></div></div>
    <p className="muted">{leader?`Lead: ${leader.firstName} ${leader.lastName} (${Math.round(relationScore(state,leader.id)??0)})`:'No current lead'}{rival?` · Rival: ${rival.firstName} ${rival.lastName} (${Math.round(view.rivalry)} pressure)`:''}</p>
    {view.kind==='acting'&&career.currentProjectActive===true&&career.currentProjectWorldId===world.id&&<p className="memory">In production: {String(career.currentProjectRole??'role')} · booked pay {formatMoney(Number(career.currentProjectPay??0))}. Release resolves on the next Age Up.</p>}
    {view.kind==='directing'&&career.currentProjectActive===true&&career.currentProjectWorldId===world.id&&<p className="memory">In production: {formatMoney(Number(career.currentProjectBudget??0))} budget · {String(career.currentProjectSource??'production')} · director fee {formatMoney(Number(career.currentProjectFee??0))}. Release resolves on the next Age Up.</p>}
    {view.kind==='music'&&career.lastReleaseTitle&&<p className="memory">Latest release: <strong>{String(career.lastReleaseTitle)}</strong> · {String(career.lastReleaseReception??'released')} · launch {Number(career.lastReleaseStreams??0).toLocaleString()} streams · latest catalog tail {Number(career.lastCatalogTailStreams??0).toLocaleString()}.</p>}
    {view.kind==='music'&&<p className="memory">Audience: {Number(career.fanbase??0).toLocaleString()} fans · catalog {Number(career.catalogLifetimeStreams??0).toLocaleString()} lifetime streams · management pressure {Math.round(Number(career.managementPressure??0))}/100.</p>}
    {view.kind==='music'&&career.tourActive===true&&<p className="memory">On the road: {String(career.currentTourName??'Tour')} · {Number(career.currentTourShows??0)} {String(career.currentTourScale??'')} shows. Attendance, costs, fatigue, and career impact resolve on the next Age Up.</p>}
    {view.kind==='music'&&career.distributionPartner===true&&<p className="memory">Distribution: {String(career.distributionPartnerName??'partner')} · {Math.round((Number(career.distributionReach??1)-1)*100)}% reach boost · {Math.round(Number(career.distributionShare??0)*100)}% royalty share.</p>}
    {view.kind==='modeling'&&career.campaignActive===true&&<p className="memory">Booked campaign: <strong>{String(career.currentCampaignTitle??'Campaign')}</strong> · {String(career.currentCampaignKind??'campaign')} · {formatMoney(Number(career.currentCampaignGross??0))} gross. Completion resolves on the next Age Up.</p>}
    {view.kind==='modeling'&&career.lastCampaignTitle&&<p className="memory">Latest campaign: <strong>{String(career.lastCampaignTitle)}</strong> · {String(career.lastCampaignReception??'completed')} · {Math.round(Number(career.lastCampaignScore??0))}/100 · net {formatMoney(Number(career.lastCampaignNet??0))}.</p>}
    {view.kind==='modeling'&&career.agencyContractActive===true&&<p className="memory">Representation: {String(career.agencyName??world.name)} · {Number(career.agencyContractRemaining??0)} year{Number(career.agencyContractRemaining??0)===1?'':'s'} remaining · {Math.round(Number(career.agencyCommission??0)*100)}% commission · {Math.round((Number(career.agencyReach??1)-1)*100)}% reach boost.</p>}
    {view.kind==='modeling'&&<p className="memory">Campaigns completed: {Number(career.campaignsCompleted??0)} · career earnings {formatMoney(Number(career.careerEarnings??0))} · industry pressure {Math.round(Number(career.industryPressure??0))}/100.</p>}
    {view.kind==='modeling'&&career.agencyContractActive!==true&&!modelOffer&&Number(career.jobs??0)>0&&<div className="button-row"><button disabled={!actionAllowed(state,{policy:'special.model.agency_seek'})} onClick={()=>onResult(gameEngine.modelingAgency('seek'),{primary:careerActionVfx('modeling'),derive:true})}>Seek representation</button></div>}
    {view.kind==='sports'&&career.pro===true&&<p className="memory">Contract: {contractRemaining} year{contractRemaining===1?'':'s'} remaining{salary?` · ${formatMoney(salary)}/year`:''}.</p>}
    {view.kind==='sports'&&Number(career.seasonsPlayed??0)>0&&<p className="memory">Season {Number(career.seasonsPlayed)}: {String(career.seasonRecord??'record pending')} · performance {Math.round(Number(career.lastSeasonScore??0))}/100. {String(career.seasonOutcome??'')}</p>}
    {view.kind==='sports'&&Number(career.seasonsPlayed??0)>0&&<p className="memory">Career: {Number(career.careerAppearances??0)} appearances · {Number(career.championships??0)} championship{Number(career.championships??0)===1?'':'s'} · best season {Math.round(Number(career.bestSeasonScore??0))}/100.</p>}
    {view.kind==='racing'&&career.contractActive===true&&<p className="memory">Team contract: {Number(career.contractRemaining??0)} year{Number(career.contractRemaining??0)===1?'':'s'} remaining · {formatMoney(Number(career.salary??0))}/season.</p>}
    {view.kind==='racing'&&career.seasonActive===true&&<p className="memory">Season underway: {Number(career.currentSeasonRaces??0)} rounds with {String(career.currentSeasonTeam??world.name)}. Results settle on the next Age Up.</p>}
    {view.kind==='racing'&&Number(career.seasons??0)>0&&<p className="memory">Latest championship: P{Number(career.lastChampionshipPosition??20)} · {Number(career.lastSeasonWins??0)} wins · {Number(career.lastSeasonPodiums??0)} podiums · {Number(career.lastSeasonPoints??0)} points · score {Math.round(Number(career.lastSeasonScore??0))}/100.</p>}
    {view.kind==='racing'&&Number(career.seasons??0)>0&&<p className="memory">Career: {Number(career.seasons??0)} seasons · {Number(career.careerWins??0)} wins · {Number(career.careerPodiums??0)} podiums · {Number(career.titles??0)} championship{Number(career.titles??0)===1?'':'s'} · team pressure {Math.round(Number(career.teamPressure??0))}/100.</p>}
    {(awards>0||scandals>0)&&<p className="memory">Career record: {awards} award{awards===1?'':'s'} · {scandals} public scandal{scandals===1?'':'s'}.</p>}
    <div className="button-row"><button disabled={!peer||!interactionAllowed(state,peer.id,'spend_time')} onClick={()=>interact(peer,'spend_time',{primary:'chemistryGain',derive:true,suppressDerived:['relationshipGain']})}>Build chemistry</button><button disabled={!leader||!interactionAllowed(state,leader.id,'conversation')} onClick={()=>interact(leader,'conversation')}>Seek guidance</button>{rival&&<button className="secondary-button" disabled={!interactionAllowed(state,rival.id,'conversation')} onClick={()=>interact(rival,'conversation')}>Ease rivalry</button>}</div>
  </article>;
}
