import { useState } from 'react';
import type { EngineResult, GameState, Npc, SocialWorld } from '../types/game';
import { BottomSheet } from './BottomSheet';
import { gameEngine } from '../stores/gameStore';
import { actionAllowed } from '../core/actionEconomy';
import { formatMoney } from '../core/format';
import { specialCareerWorldKind, specialCareerWorldView, type SpecialCareerWorldView } from '../systems/SpecialCareerEcosystemSystem';
import { screenCareerOffer } from '../systems/ScreenCareerCycleSystem';
import { musicCatalog, musicPartnershipOffer } from '../systems/MusicCareerCycleSystem';
import { modelingAgencyOffer, modelingCampaignHistory } from '../systems/ModelingCareerCycleSystem';
import type { SpecialCareerWorldKind } from '../systems/SpecialCareerWorldSystem';

const KIND_LABELS:Record<SpecialCareerWorldKind,string>={acting:'Acting production',music:'Music collective',sports:'Professional team',modeling:'Modeling network',racing:'Race team',directing:'Film production'};
type CareerTrack=Record<string,number|string|boolean>;
function careerTrack(state:GameState,kind:SpecialCareerWorldKind){return (state.specialCareers[kind]??{}) as CareerTrack;}
function person(state:GameState,id?:string):Npc|undefined{return id?state.npcs[id]:undefined;}
function relationScore(state:GameState,id?:string){return id?state.relationships.find(rel=>rel.npcId===id)?.score:undefined;}
function interactionAllowed(state:GameState,id:string|undefined,action:string){return Boolean(id)&&actionAllowed(state,[{policy:'social.npc.total',target:id!},{policy:'social.npc.action',target:`${id}:${action}`}]);}
function resolvedImpact(world:SocialWorld){return world.groups.find(group=>group.kind.endsWith(':resolved'))?.prestige;}
function worldSort(a:SocialWorld,b:SocialWorld){return Number(b.active)-Number(a.active)||b.startedAge-a.startedAge||b.id.localeCompare(a.id);}

export function SpecialCareerWorldPanel({state,onResult}:{state:GameState;onResult:(result:EngineResult)=>void}){
  const[open,setOpen]=useState(false);const worlds=state.socialWorlds.filter(world=>Boolean(specialCareerWorldKind(world))).slice().sort(worldSort);const active=worlds.filter(world=>world.active);const history=worlds.filter(world=>!world.active).slice(0,8);
  const actingOffer=screenCareerOffer(state,'acting');const directingOffer=screenCareerOffer(state,'directing');const musicOffer=musicPartnershipOffer(state);const modelingOffer=modelingAgencyOffer(state);const offerCount=Number(Boolean(actingOffer))+Number(Boolean(directingOffer))+Number(Boolean(musicOffer))+Number(Boolean(modelingOffer));
  const actingActive=active.some(world=>specialCareerWorldKind(world)==='acting');const directingActive=active.some(world=>specialCareerWorldKind(world)==='directing');const hasContent=worlds.length>0||offerCount>0;
  const acting=careerTrack(state,'acting');const directing=careerTrack(state,'directing');const music=careerTrack(state,'music');const modeling=careerTrack(state,'modeling');const catalog=musicCatalog(state).slice(0,6);const modelHistory=modelingCampaignHistory(state).slice(0,6);
  return <>
    <section className="action-card"><div className="section-heading"><div><p className="eyebrow">Persistent career worlds</p><h2>{active.length?`${active.length} active ${active.length===1?'ecosystem':'ecosystems'}`:'Career ecosystem'}</h2></div><span>{offerCount?`${offerCount} offer${offerCount===1?'':'s'}`:`${worlds.length} total`}</span></div>
      {active.length?<p className="muted">{active.slice(0,3).map(world=>world.name).join(' · ')}{active.length>3?` · +${active.length-3} more`:''}. Cast, team, staff, creative partners, and rival relationships feed directly into career outcomes.</p>:offerCount?<p className="muted">Your recent work generated a follow-up opportunity. Offers expire with age and still respect the normal career action limits.</p>:<p className="muted">Book an acting role, release music, turn professional in sports, land modeling work, enter motorsport, or direct a film to create a persistent career world.</p>}
      <div className="button-row"><button disabled={!hasContent} onClick={()=>setOpen(true)}>{offerCount?'Review career offers':active.length?'Open career worlds':'View career history'}</button></div></section>
    <BottomSheet open={open} title="Career worlds" onClose={()=>setOpen(false)} wide>
      {offerCount>0&&<div className="sheet-section"><h3>Pending offers</h3>
        {actingOffer&&<article className="school-group-card joined"><div><strong>Acting offer · {actingOffer.role}</strong><small>From {actingOffer.sourceProject} · {formatMoney(actingOffer.pay??0)} · expires after age {actingOffer.expiresAge}</small></div><div className="school-group-actions"><button disabled={actingActive||!actionAllowed(state,{policy:'special.audition'})} onClick={()=>onResult(gameEngine.actingAudition())}>Accept role</button></div></article>}
        {directingOffer&&<article className="school-group-card joined"><div><strong>Studio-backed directing offer</strong><small>From {directingOffer.sourceProject} · {formatMoney(directingOffer.budget??0)} budget · {formatMoney(directingOffer.fee??0)} fee · expires after age {directingOffer.expiresAge}</small></div><div className="school-group-actions"><button disabled={directingActive||!actionAllowed(state,{policy:'special.direct_film'})} onClick={()=>onResult(gameEngine.directFilm(directingOffer.budget??1500000))}>Accept film</button></div></article>}
        {musicOffer&&<article className="school-group-card joined"><div><strong>Music distribution offer · {musicOffer.partner}</strong><small>From {musicOffer.sourceRelease} · {formatMoney(musicOffer.advance)} advance · {Math.round(musicOffer.royaltyShare*100)}% royalty share · {Math.round((musicOffer.reach-1)*100)}% reach boost · expires after age {musicOffer.expiresAge}</small></div><div className="school-group-actions"><button disabled={!actionAllowed(state,{policy:'special.music_business'})} onClick={()=>onResult(gameEngine.musicPartnership('accept'))}>Accept partnership</button><button className="secondary-button" disabled={!actionAllowed(state,{policy:'special.music_business'})} onClick={()=>onResult(gameEngine.musicPartnership('decline'))}>Decline</button></div></article>}
        {modelingOffer&&<article className="school-group-card joined"><div><strong>{modelingOffer.kind==='renewal'?'Agency renewal':'Modeling representation'} · {modelingOffer.agency}</strong><small>{modelingOffer.years} years · {Math.round(modelingOffer.commission*100)}% commission · {Math.round((modelingOffer.reach-1)*100)}% booking-reach boost · expires after age {modelingOffer.expiresAge}</small></div><div className="school-group-actions"><button disabled={!actionAllowed(state,{policy:'special.model.business'})} onClick={()=>onResult(gameEngine.modelingAgency('accept'))}>Accept contract</button><button className="secondary-button" disabled={!actionAllowed(state,{policy:'special.model.business'})} onClick={()=>onResult(gameEngine.modelingAgency('decline'))}>Decline</button></div></article>}
      </div>}
      {active.length>0&&<div className="sheet-section"><h3>Active ecosystems</h3>{active.map(world=><CareerWorldCard key={world.id} state={state} world={world} onResult={onResult}/>)}</div>}
      {catalog.length>0&&<div className="sheet-section"><h3>Recent music catalog</h3>{catalog.map(entry=><p className="memory" key={`${entry.slot}-${entry.title}-${entry.launchAge}`}><strong>{entry.title}</strong> · {entry.kind} · age {entry.launchAge} · {entry.reception} · launch {entry.launchStreams.toLocaleString()} · lifetime {entry.lifetimeStreams.toLocaleString()} streams</p>)}</div>}
      {modelHistory.length>0&&<div className="sheet-section"><h3>Recent modeling campaigns</h3>{modelHistory.map(entry=><p className="memory" key={`${entry.slot}-${entry.title}-${entry.completedAge}`}><strong>{entry.title}</strong> · {entry.kind} · completed age {entry.completedAge} · {entry.reception} · {Math.round(entry.score)}/100 · net {formatMoney(entry.netPay)}</p>)}</div>}
      {(acting.lastProjectName||directing.lastProjectName||music.lastTourName||modeling.lastCampaignTitle)&&<div className="sheet-section"><h3>Latest major releases & tours</h3>
        {acting.lastProjectName&&<p className="memory"><strong>{String(acting.lastProjectName)}</strong> · {String(acting.lastProjectRole??'role')} · {String(acting.lastProjectReception??'released')} · impact {Math.round(Number(acting.lastProjectScore??0))}/100{Number(acting.lastProjectBonus??0)>0?` · bonus ${formatMoney(Number(acting.lastProjectBonus))}`:''}</p>}
        {directing.lastProjectName&&<p className="memory"><strong>{String(directing.lastProjectName)}</strong> · {String(directing.lastProjectReception??'released')} · impact {Math.round(Number(directing.lastProjectScore??0))}/100 · box office {formatMoney(Number(directing.lastBoxOffice??0))}</p>}
        {music.lastTourName&&<p className="memory"><strong>{String(music.lastTourName)}</strong> · {String(music.lastTourScale??'tour')} · {Number(music.lastTourShows??0)} shows · performance {Math.round(Number(music.lastTourScore??0))}/100 · net {formatMoney(Number(music.lastTourNet??0))}</p>}
        {modeling.lastCampaignTitle&&<p className="memory"><strong>{String(modeling.lastCampaignTitle)}</strong> · {String(modeling.lastCampaignKind??'campaign')} · {String(modeling.lastCampaignReception??'completed')} · performance {Math.round(Number(modeling.lastCampaignScore??0))}/100 · net {formatMoney(Number(modeling.lastCampaignNet??0))}</p>}
      </div>}
      {history.length>0&&<div className="sheet-section"><h3>Career history</h3>{history.map(world=>{const kind=specialCareerWorldKind(world)!;const impact=resolvedImpact(world);return <p className="memory" key={world.id}><strong>{world.name}</strong> · {KIND_LABELS[kind]} · ages {world.startedAge}–{world.endedAge??state.character.age}{impact!==undefined?` · impact ${Math.round(impact)}/100`:''}</p>})}</div>}
      {!hasContent&&<p className="muted">No special-career worlds or offers have been created in this life yet.</p>}
    </BottomSheet>
  </>;
}

function CareerWorldCard({state,world,onResult}:{state:GameState;world:SocialWorld;onResult:(result:EngineResult)=>void}){
  const view=specialCareerWorldView(state,world) as SpecialCareerWorldView;const career=careerTrack(state,view.kind);const leader=person(state,view.leaderNpcId);const rival=person(state,view.rivalNpcId);const peer=person(state,view.peerNpcId);const momentum=Math.round(Number(career.careerMomentum??0));const awards=Number(career.awards??0);const scandals=Number(career.scandals??0);const project=view.kind==='acting'||view.kind==='directing';const interact=(npc:Npc|undefined,action:string)=>{if(npc)onResult(gameEngine.interactWithCharacter(npc.id,action));};const contractRemaining=Number(career.contractRemaining??career.contractYears??0);const salary=Number(career.salary??0);
  const modelOffer=view.kind==='modeling'?modelingAgencyOffer(state):undefined;
  return <article className="school-group-card joined"><div className="section-heading"><div><p className="eyebrow">{KIND_LABELS[view.kind]}</p><h3>{world.name}</h3></div><span>{view.memberCount} people</span></div>
    <div className="sheet-stat-grid">{!project&&<div><small>Momentum</small><strong>{momentum||'—'}</strong></div>}<div><small>Chemistry</small><strong>{Math.round(view.chemistry)}</strong></div><div><small>Prestige</small><strong>{Math.round(view.prestige)}</strong></div><div><small>Rivalry</small><strong>{Math.round(view.rivalry)}</strong></div></div>
    <p className="muted">{leader?`Lead: ${leader.firstName} ${leader.lastName} (${Math.round(relationScore(state,leader.id)??0)})`:'No current lead'}{rival?` · Rival: ${rival.firstName} ${rival.lastName} (${Math.round(view.rivalry)} pressure)`:''}</p>
    {view.kind==='acting'&&career.currentProjectActive===true&&career.currentProjectWorldId===world.id&&<p className="memory">In production: {String(career.currentProjectRole??'role')} · booked pay {formatMoney(Number(career.currentProjectPay??0))}. Release resolves on the next Age Up.</p>}
    {view.kind==='directing'&&career.currentProjectActive===true&&career.currentProjectWorldId===world.id&&<p className="memory">In production: {formatMoney(Number(career.currentProjectBudget??0))} budget · {String(career.currentProjectSource??'production')} · director fee {formatMoney(Number(career.currentProjectFee??0))}. Release resolves on the next Age Up.</p>}
    {view.kind==='music'&&career.lastReleaseTitle&&<p className="memory">Latest release: <strong>{String(career.lastReleaseTitle)}</strong> · {String(career.lastReleaseReception??'released')} · launch {Number(career.lastReleaseStreams??0).toLocaleString()} streams · latest catalog tail {Number(career.lastCatalogTailStreams??0).toLocaleString()}.</p>}
    {view.kind==='music'&&<p className="memory">Audience: {Number(career.fanbase??0).toLocaleString()} fans · catalog {Number(career.catalogLifetimeStreams??0).toLocaleString()} lifetime streams · management pressure {Math.round(Number(career.managementPressure??0))}/100.</p>}
    {view.kind==='music'&&<p className="muted">This collective is your persistent creative/management circle. Distribution offers are separate business terms, so an expired offer does not erase these relationships or their career history.</p>}
    {view.kind==='music'&&career.tourActive===true&&<p className="memory">On the road: {String(career.currentTourName??'Tour')} · {Number(career.currentTourShows??0)} {String(career.currentTourScale??'')} shows. Attendance, costs, fatigue, and career impact resolve on the next Age Up.</p>}
    {view.kind==='music'&&career.distributionPartner===true&&<p className="memory">Distribution: {String(career.distributionPartnerName??'partner')} · {Math.round((Number(career.distributionReach??1)-1)*100)}% reach boost · {Math.round(Number(career.distributionShare??0)*100)}% royalty share.</p>}
    {view.kind==='modeling'&&career.campaignActive===true&&<p className="memory">Booked campaign: <strong>{String(career.currentCampaignTitle??'Campaign')}</strong> · {String(career.currentCampaignKind??'campaign')} · {formatMoney(Number(career.currentCampaignGross??0))} gross. Completion resolves on the next Age Up.</p>}
    {view.kind==='modeling'&&career.lastCampaignTitle&&<p className="memory">Latest campaign: <strong>{String(career.lastCampaignTitle)}</strong> · {String(career.lastCampaignReception??'completed')} · {Math.round(Number(career.lastCampaignScore??0))}/100 · net {formatMoney(Number(career.lastCampaignNet??0))}.</p>}
    {view.kind==='modeling'&&career.agencyContractActive===true&&<p className="memory">Representation: {String(career.agencyName??world.name)} · {Number(career.agencyContractRemaining??0)} year{Number(career.agencyContractRemaining??0)===1?'':'s'} remaining · {Math.round(Number(career.agencyCommission??0)*100)}% commission · {Math.round((Number(career.agencyReach??1)-1)*100)}% reach boost.</p>}
    {view.kind==='modeling'&&<p className="memory">Campaigns completed: {Number(career.campaignsCompleted??0)} · career earnings {formatMoney(Number(career.careerEarnings??0))} · industry pressure {Math.round(Number(career.industryPressure??0))}/100.</p>}
    {view.kind==='modeling'&&career.agencyContractActive!==true&&!modelOffer&&Number(career.jobs??0)>0&&<div className="button-row"><button disabled={!actionAllowed(state,{policy:'special.model.agency_seek'})} onClick={()=>onResult(gameEngine.modelingAgency('seek'))}>Seek representation</button></div>}
    {view.kind==='sports'&&career.pro===true&&<p className="memory">Contract: {contractRemaining} year{contractRemaining===1?'':'s'} remaining{salary?` · ${formatMoney(salary)}/year`:''}.</p>}
    {view.kind==='sports'&&Number(career.seasonsPlayed??0)>0&&<p className="memory">Season {Number(career.seasonsPlayed)}: {String(career.seasonRecord??'record pending')} · performance {Math.round(Number(career.lastSeasonScore??0))}/100. {String(career.seasonOutcome??'')}</p>}
    {view.kind==='sports'&&Number(career.seasonsPlayed??0)>0&&<p className="memory">Career: {Number(career.careerAppearances??0)} appearances · {Number(career.championships??0)} championship{Number(career.championships??0)===1?'':'s'} · best season {Math.round(Number(career.bestSeasonScore??0))}/100.</p>}
    {(awards>0||scandals>0)&&<p className="memory">Career record: {awards} award{awards===1?'':'s'} · {scandals} public scandal{scandals===1?'':'s'}.</p>}
    <div className="button-row"><button disabled={!peer||!interactionAllowed(state,peer.id,'spend_time')} onClick={()=>interact(peer,'spend_time')}>Build chemistry</button><button disabled={!leader||!interactionAllowed(state,leader.id,'conversation')} onClick={()=>interact(leader,'conversation')}>Seek guidance</button>{rival&&<button className="secondary-button" disabled={!interactionAllowed(state,rival.id,'conversation')} onClick={()=>interact(rival,'conversation')}>Ease rivalry</button>}</div>
    <p className="muted">These use the normal NPC relationship limits. Chemistry affects next-year momentum, release/tour performance, campaign results, or project impact; hostile rivalry and weak chemistry increase pressure.</p>
  </article>;
}
